### ISSUE TITLE
Use 'keywordprg' instead of remapping K

### ISSUE THREAD

**Issue by hauleth** [natebosch/vim-lsc#101]

**Comment by natebosch** [comment]
I think this might be breaking for some edge cases in user config, but I think that it probably won't impact many users.

What benefits will this bring?

**Comment by hauleth** [comment]
It will be more "in line" with Vim features. And it shouldn't break anything as you can ignore arguments passed to the command and do whatever you like anyway. So it will be rather cosmetic change to get in line on "how it should be done".

Only edge cases where it would broke are:

- someone mapped docs to something else than `K`
- someone `noremap`ped `K` to other chord to use it anyway

**Comment by natebosch** [comment]
I do like consistency with vim conventions :)

I think I've got it backwards compatible so if someone was setting some mapping other than `K` it should still work.
