### ISSUE TITLE
Support documentChanges property of WorkspaceEdit

### ISSUE THREAD

**Issue by mwilliammyers** [natebosch/vim-lsc#105]
Currently only the `changes` property of a [`WorkspaceEdit`](https://microsoft.github.io/language-server-protocol/specification#workspaceedit) is supported.

I have a patch ready to go and would be happy to open a PR to add support for the preferred (by the LSP) `documentChanges` property.

**Comment by natebosch** [comment]
I think the reason I had avoided this was that I couldn't reasonably support the expectations around document versions.

If a server is sending this today and _not_ sending `changes` I think it's out of spec. This client does not advertise support in `workspace.workspaceEdit.documentChanges` in the `ClientCapabilities` so the server shouldn't be relying on it working.

I think I could be convinced that we should fake the support and just ignore the version stuff - or I could be convinced to put some more effort into being able to support the version checking. Do you have any thoughts on that?

**Comment by mwilliammyers** [comment]
It depends on how frequently we think that servers will disobey the spec. If the most popular language server (Atom and VSCode use it) for one of the most popular languages isn't even following spec, it seems like we might run into this issue frequently? 

It also depends on how much complexity it will add to just fake support for the given operation. In this case it wasn't too bad in my opinion; although my patch completely ignores workspace.workspaceEdit.documentChanges` and `workspace.workspaceEdit.resourceOperations`.

I am not really sure what implementing versioned documents (`documentChanges`) would entail - being able to support undo/redo? `resourceOperations` might be cool to support - being able to rename files and have e.g. python imports change (not sure if that is what the spec had in mind). Both seem non trivial to implement...

I wonder if I should just open an issue on [palantir/python-language-server](https://github.com/palantir/python-language-server) to see what they say about better following the spec?

**Comment by natebosch** [comment]
@mwilliammyers - sorry for the long silence.

If you want to open up a PR with that patch I think it's fine to handle `documentChanges` even without full version handling.
