### ISSUE TITLE
How to configure vim-lsc to work with cquery?

### ISSUE THREAD

**Issue by Piping** [natebosch/vim-lsc#106]
Hi,

I have trouble setup the client to talk to `clangd` or `cquery` (these two are language servers).

Here it is my setup. Thanks

```vim
    Plug 'natebosch/vim-lsc'
    let g:lsc_server_commands = { 'cpp':'clangd-6.0'}
```

**Comment by aravind2612krishna** [comment]
For clangd your statement is correct, except that instead of clangd-6.0 you give 'çlangd'

For cquery:
let g:lsc_server_commands = {
            \ 'c': "cquery --init=\"{\\\"cacheDirectory\\\": \\\"C:/Temp/cquery\\\"}\"",
            \ 'cpp': "cquery --init=\"{\\\"cacheDirectory\\\": \\\"C:/Temp/cquery\\\"}\""
            \ }


Make sure that "cquery.exe" or "clangd.exe" is in your path. (PATH environment variable)

**Comment by Piping** [comment]
@aravind2612krishna Thanks a lot. These escape character is hard to get right!
Here it is my setup for future new comer.
```vim
     Plug 'natebosch/vim-lsc'
     let g:lsc_server_commands = {
                 \ 'c': 'cquery --init="{\"cacheDirectory\": \"/tmp/cquery_cache\"}"',
                 \ 'cpp': 'cquery --init="{\"cacheDirectory\": \"/tmp/cquery_cache\"}"',
                 \ 'python' : 'pyls',
                 \ }
```
