### ISSUE TITLE
How to disable new notification and error message?

### ISSUE THREAD

**Issue by Piping** [natebosch/vim-lsc#107]
Hi,

Is it possible to disable the notification sent by language server?

**Comment by natebosch** [comment]
Which notifications in particular? Are you synced past https://github.com/natebosch/vim-lsc/commit/d355fb575e9e5e2f85c3763c779285e66e656fa8 where notifications starting with `$` are ignored?

**Comment by Piping** [comment]
Hi,

The notification I am referring to is 

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/12042284/46887530-bc60e500-ce12-11e8-86fa-f76e0b3f974e.png">

Is this notification started with $?

**Comment by natebosch** [comment]
> Is this notification started with $?

Yes, looks like it's `$cquery/` so it should be covered by that check. Can you make sure you're updated to the latest version of this plugin and let me know if it's still a problem for you?

> Btw, is it possible to enable wiki editing for public? So some setup codes can be pasted there by crowd?

Good idea! I set the wiki to allow contributions and started a page at https://github.com/natebosch/vim-lsc/wiki/Server-Configurations

**Comment by natebosch** [comment]
Ah, the spec talks about `$/` but it looks like this server doesn't quite follow the spec and uses `$cquery/`... I can't think of an immediate reason not to ignore anything staring with `$` so I'll go with that for now. Sync to the latest and this should hopefully be working for you now.
