### ISSUE TITLE
null insertText on textDocument/completion breaks the completion

### ISSUE THREAD

**Issue by pawel-slowik** [natebosch/vim-lsc#110]
The [php-language-server](https://github.com/felixfbecker/php-language-server/) can respond to `textDocument/completion` with an item that looks like this:

```
{
    "label":"getContainer",
    "kind":2,
    "detail":"\\Psr\\Container\\ContainerInterface",
    "documentation":"Enable access to the DI container by consumers of $app",
    "sortText":null,
    "filterText":null,
    "insertText":null,
    "textEdit":null,
    "additionalTextEdits":null,
    "command":null,
    "data":null
},
```
This results in a null `item.word` in the [`CompletionItem` function](https://github.com/natebosch/vim-lsc/blob/3949861c954fa9fec475bd839ed8e88cb6383c06/autoload/lsc/complete.vim#L232), which makes completion unusable.

I think that in this case the php-l-s breaks [the spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion), because the `insertText` property, if set, must be a string. It must not be null. On the other hand, the same spec says that in case of a "falsy" `insertText` the `label` is used instead.

IMO it would be a good idea to test `insertText` with !empty():
```viml
  elseif has_key(a:completion_item, 'insertText')
      \ && !empty(a:completion_item.insertText)
    let item.word = a:completion_item.insertText
```
This would eliminate nulls as well as falsy strings.

**Comment by natebosch** [comment]
> I think that in this case the php-l-s breaks the spec

That's my understanding as well.

> IMO it would be a good idea to test insertText with !empty():

I agree! I don't see any reason to fail hard just because a server isn't 100% to spec.
