### ISSUE TITLE
Missing initialized notification

### ISSUE THREAD

**Issue by olafurpg** [natebosch/vim-lsc#113]
I was trying vim-lsc with a language server that I'm developing and I noticed that the `initialized` notification is not sent after the `initialize` request is responded.

https://microsoft.github.io/language-server-protocol/specification#initialized

My language server uses this notification to start indexing the workspace sources and initialize a connection with a build server. The lack of the `initialized` notification means that functionality like `textDocument/definition` doesn't work.

I took a stab at implementing this myself but failed due to my limited experience with vim script. 

PS Thanks for implementing such a lightweight vim client!

**Comment by olafurpg** [comment]
FWIW, a workaround on the server side is to internally call `initialized` before responding to the `initialize` request.

**Comment by natebosch** [comment]
Interesting, not sure why this request would be necessary - I can't think of a reason that a client wouldn't always call it immediately after the `initialized` response comes back... In any case it should be easy to add.

**Comment by olafurpg** [comment]
@natebosch Thank you for the fix! I opened https://github.com/natebosch/vim-lsc/pull/116 to change a typo in the notification method.

The `initialized` notification is handy for the server to know that stdin/stdout communication works in all directions (client -> server and server -> client).
