### ISSUE TITLE
Missing textDocument/didSave notification

### ISSUE THREAD

**Issue by olafurpg** [natebosch/vim-lsc#114]
When saving a file with `:w` the vim-lsc client currently does not send a `textDocument/didSave` notification. This notification is useful for a language server to trigger batch compilation in the background or perform further analysis that is too expensive to run on every `textDocument/didChange`.

**Comment by natebosch** [comment]
@olafurpg - the client currently does not support any of the notification registration stuff - is that important to you or will it be enough to unconditionally send the `textDocument/didSave` notification?

**Comment by olafurpg** [comment]
@natebosch Unconditional `textDocument/didSave` is the expected behavior. I've updated and can confirm it's working now, thank you for the fix!

**Comment by natebosch** [comment]
Heads up @olafurpg - I'll be changing the behavior here to closer match the spec.
https://github.com/natebosch/vim-lsc/issues/164

If your server either omits the `textDocumentSync` capability, or it includes it as a dict that omits the `save` key, we won't send a `didSave`. If it's sending a `TextDocumentSyncKind` number, or includes the `save` key in it's dict we will send it.

**Comment by olafurpg** [comment]
@natebosch thanks for the heads up! We send an explicit `TextDocumentSyncKind` in our server :)
