### ISSUE TITLE
Exit notification should wait for shutdown response

### ISSUE THREAD

**Issue by olafurpg** [natebosch/vim-lsc#118]
Currently, the `exit` notification is sent immediately after the `shutdown` request

https://github.com/natebosch/vim-lsc/blob/d19237349e42ea3b515e97b9a8f745b7e9febacb/autoload/lsc/server.vim#L43-L44

I expected the `exit` notification to be sent as a callback to the `shutdown` response. In [a language server](https://scalameta.org/metals/) I'm developing, we persist incremental compile cache during shutdown and if the process is killed before that completes then the next startup will perform unnecessary re-compilation.

**Comment by natebosch** [comment]
We could definitely wait when the server is being closed _without_ exiting vim, such as on a `:LSClientRestartServer` call.

If we're doing this in response to the editor closing (the common case) I don't think we have a choice. We can't delay the actual process shutdown, only do a bit of synchronous work before it exits. We can't tell the editor to not shutdown until some asynchronous delay waiting for the server...

**Comment by natebosch** [comment]
Actually, come to think of it I can probably use the same trick with `sleep` as I use in the completefunc implementation... let me try to put something together.

**Comment by natebosch** [comment]
@olafurpg - should be waiting now for the response to `'shutdown'` before sending the `'exit'`.

As a consequence, if the `'shutdown'` response doesn't come within 5 seconds we might quit before sending the `'exit'`. Let me know if this is working for you. As an alternative I could wait 5 seconds and then send the `'exit'` regardless of whether we got a response.

**Comment by olafurpg** [comment]
@natebosch thank you for the fix, I can confirm that the new update waits until `shutdown` has responded or after 5 seconds when there is no response. The shutdown sequence looks just right now 🙏 

```json
{
  "jsonrpc": "2.0",
  "id": 7,
  "method": "shutdown",
  "params": null
}
{
  "jsonrpc": "2.0",
  "id": 7,
  "result": null
}
{
  "jsonrpc": "2.0",
  "method": "exit",
  "params": null
}
```
