### ISSUE TITLE
Neovim complains on undefined variable v:t_none on exit

### ISSUE THREAD

**Issue by sakhnik** [natebosch/vim-lsc#119]
Apparently, there is no `v:t_none` in neovim yet. Could you please consider fixing the check to something more portable like the following?
```vim
    if a:OnExit != v:null | call a:OnExit() | endif
```

**Comment by skeswa** [comment]
+1

**Comment by natebosch** [comment]
should be fixed now

**Comment by jvican** [comment]
I confirm it's fixed, thanks @natebosch
