### ISSUE TITLE
Notification for window/progress is too generic

### ISSUE THREAD

**Issue by fawick** [natebosch/vim-lsc#129]
Thanks @natebosch for writing vim-lsc, it makes working on Rust code so much nicer for me!

Recently I noticed that the Rust language server is emitting `window/progress` messages, which are not yet handled by vim-lsc upstream. 

I scratched my own itch and wrote a handler that is "good enough" for me (https://github.com/fawick/vim-lsc/commit/4e4a1039cf6bfd4aef6b94ad0d21ae2b5cc9b3b7). If it's something you want handled in upstream, I'd create a PR.

**Comment by natebosch** [comment]
Looks good! if you want to add an entry in CHANGELOG and open a PR I can merge it in.
