### ISSUE TITLE
LSClient keeps bugging me when I open a Javascript project

### ISSUE THREAD

**Issue by reaysawa** [natebosch/vim-lsc#133]
Every time I open the editor with a javascript file, vim-lsc insists to tell me:

```
[lsc:Log] Found package file:///home/user/js/react-native-tdd/package.json
[lsc:Log] Found package file:///home/user/js/react-native-tdd/package.json
```

I wish there was a "silent" global flag which only enabled critical warnings or errors. I'm the kind of person who silences everything, even Vim's "informational" messages.

My configuration

```
let g:lsc_trace_level = "off"
let g:lsc_server_commands  = {
    \ 'javascript' : {
    \    'command': '/usr/bin/javascript-typescript-stdio',
    \    'suppress_stderr': v:true,
    \    'message_hooks': {
    \        'initialize': {'rootUri': {method, params ->
    \            lsc#uri#documentUri(FindRootDirectory())}}},
    \    }
    \}
```

I'm fairly familiar with Vimscript by now, so you can tell me which function does the logging and I can go through the code introducing checks around it. Is it only on [message.vim](https://github.com/natebosch/vim-lsc/blob/master/autoload/lsc/message.vim)?

Also, great plugin! Thanks for developing this ^ _ ^

**Comment by natebosch** [comment]
We could make this configurable if we need, but I'm also very open to changing the default behavior.   I never had any particular need or requests for the current behavior, I only implemented it out of completeness. `showMessage` has been all I really needed.

What do you think would be better to do with a `window/logMessage` other than `echom`? Should it ignore it for now and I can wait until someone requests the ability to see `window/logMessage` messages and figure it out then? Is there something else you'd hope to be done with these other than ignore them?

Would you prefer a hook to filter them, but to still show them by default?

**Comment by reaysawa** [comment]
I'm generally open to whatever is most flexible for who is using it.

Well, taking ALE as an example, which you should have heard of, it very rarely displays tooling/verbose messages into the main screen itself - one who wants to figure any of that out has to type `:ALEInfo`, which brings up an paged window with all that sort of stuff. This has the downside of incorrectly configured processes failing silently in the background, but the upside of the user not being bothered by it unless he specifically wants to see debugging info with the command.

Similarly, I think the simplest approach would be to redirect all verbose output to a file and bring that up with a command... Say, `:LSClientLog`. But I think the filtering idea is also equally valuable given that some server might output a critical information in the wrong stream, and that would go unnoticed.

I guess my favorite option would be
1 - Make `window/logMessage` "overridable" - i.e. the user can register his custom callback to handle the messages, but the built-in callback echoes them by default. He could then register an empty callback that does nothing, and this would be sorta solved?
2 - Add a command `:LSClientLog` which brings up every message spat out by the server, with regards to the trace level option.

**Comment by natebosch** [comment]
Can you try out https://github.com/natebosch/vim-lsc/pull/135 ?

By default the specific messages you reference will now be hidden, only Warning or Error messages will be shown. You can override that with a per-server configuration, either filtering all the way down to Error only (or disabling echo altogether by setting it to `-1` I suppose), or re-enabling Info or Log messages to be shown.

I've got the plumbing in there for something like `:LSClientLog` but haven't implemented that command.
