### ISSUE TITLE
Enable the use of documentChanges or changes for edits

### ISSUE THREAD

**Issue by gagbo** [natebosch/vim-lsc#136]
According to the [specification](https://microsoft.github.io/language-server-protocol/specification)

>WorkspaceEdit
A workspace edit represents changes to many resources managed in the workspace. The edit should either provide changes or documentChanges. If the client can handle versioned document edits and if documentChanges are present, the latter are preferred over changes.

I ran into this issue trying to use the plugin with [ccls](https://github.com/MarkRay/ccls) because it uses the `documentChanges` key in its response to a rename call.

**Comment by gagbo** [comment]
Turns out, `vim-lsc` should actually report it doesn't handle `workspace.workspaceEdit.documentChanges` as there is a difference between the two formulations.

I don't know if the client currently does it (in this case, I should close that and try to see what happens in ccls), or if it doesn't (and the reporting should be done so servers adapt)

**Comment by gagbo** [comment]
I don't know if @mwilliammyers finished his patch or not, or has it somewhere accessible. In the mean time, here's how I patched the edit functions to extract the changes even if we only receive documentChanges : 

```patch
diff --git a/autoload/lsc/edit.vim b/autoload/lsc/edit.vim
index 985c5b0..e7ad4f1 100644
--- a/autoload/lsc/edit.vim
+++ b/autoload/lsc/edit.vim
@@ -106,7 +106,15 @@ endfunction
 function! lsc#edit#apply(workspace_edit) abort
   if (exists('g:lsc_enable_apply_edit')
       \ && !g:lsc_enable_apply_edit)
-      \ || !has_key(a:workspace_edit, 'changes')
+    return v:false
+  endif
+  if has_key(a:workspace_edit, 'changes')
+    let l:change_key = 'changes'
+    let l:is_d_change = v:false
+  elseif has_key(a:workspace_edit, 'documentChanges')
+    let l:change_key = 'documentChanges'
+    let l:is_d_change = v:true
+  else
     return v:false
   endif
   let view = winsaveview()
@@ -119,7 +127,7 @@ function! lsc#edit#apply(workspace_edit) abort
   set selection=exclusive
   set virtualedit=onemore
   try
-    call s:ApplyAll(a:workspace_edit.changes)
+    call s:ApplyAll(a:workspace_edit[l:change_key], l:is_d_change)
   finally
     if len(alternate) > 0 | let @#=alternate | endif
     if old_buffer != bufnr('%') | execute 'buffer' old_buffer | endif
@@ -131,8 +139,17 @@ function! lsc#edit#apply(workspace_edit) abort
   return v:true
 endfunction
 
-function! s:ApplyAll(changes) abort
-  for [uri, edits] in items(a:changes)
+function! s:ApplyAll(changes, is_d_change) abort
+    if !a:is_d_change
+      let l:changes = a:changes
+    else
+      "TODO : What about multiple documents ?
+      let l:changes = {}
+      for l:d_change in a:changes
+        let l:changes[d_change["textDocument"]["uri"]] = d_change["edits"]
+      endfor
+    endif
+  for [uri, edits] in items(l:changes)
     let l:file_path = lsc#uri#documentPath(uri)
     let l:bufnr = bufnr(l:file_path)
     let l:cmd = 'keepjumps keepalt'
```

Note that I only tested it on a single file "project", and I don't know the protocol either, so it's really a hack and I don't know if it works at all on big, multi-file projects. It's mainly here to show what I meant I guess

**Comment by natebosch** [comment]
We don't currently respond with any information for `workspace.workspaceEdit.documentChanges` which the server should treat as if we had specified `false`. We could make it explicit, but it's a server bug currently if it's not honoring this.

https://github.com/natebosch/vim-lsc/blob/64701d7ab33e45b6d25bd2a301c0aebb07e83126/autoload/lsc/server.vim#L207-L209

As mentioned in the linked issue, I think we can't easily support the full behavior for `documentChanges`, but I think it would likely also be fine to fake it and apply the changes even if there is version skew.

**Comment by gagbo** [comment]
I haven't checked thoroughly, but it looks like we're always going to have a `0` version identifier. In this case, would it be okay to just strip the URI from the more complex key like in the patch above ?

**Comment by natebosch** [comment]
> but it looks like we're always going to have a `0` version identifier.

Do you mean always `0` coming from the server, that would imply a server bug? The client does send monotonically increasing version identifiers with `didChange` messages:

https://github.com/natebosch/vim-lsc/blob/406f0b0881f5b8f7e3c9b18cdb91bb082942d81b/autoload/lsc/file.vim#L123

The main problem is that we only update that version when we _send_ the update, not when there _is_ an update, and we debounce the updates. So that might me that the buffer has been edited, and both the server and client agree on the version even though it's wrong.

> would it be okay to just strip the URI from the more complex key like in the patch above?

I think it probably would be okay. We can investigate if there are problems reported. It seems to me that this is no worse than today where we don't take version into account anyway. The only new problem is that the server will think we are taking version into account and may do something different - though I have no idea what it would do.

**Comment by gagbo** [comment]
Maybe I only had 0s because I did not test renaming that many times. I'll try to check whenever I have a few minutes to set this up again.

If we still do not advertise the `documentChanges` capability, I don't think it's too bad if we just ignore the versions from the server.
- If the server follows protocol closely, we're not getting the potentially problematic documentChanges messages in the first place
- If the server does not follow protocol closely (like ccls in this case), I suppose that the version number will not move too much if we always send the same message to request changes and always strip URIs from answers ? Not sure though.
