### ISSUE TITLE
FreeBSD: List is not implemented in gtk error

### ISSUE THREAD

**Issue by jan0sch** [natebosch/vim-lsc#143]
Hi,

I just tried metals with neovim on FreeBSD 11.2 and got the following error message:

```
[lsc:Error] StdErr from metals-vim: ^@(<unknown>:22541): GVFS-RemoteVolumeMonitor-WARNING **: 10:3...List is not implemented on interface org.gtk.Private.RemoteVolumeMonitor (g-dbus-error-quark, 19)^@
```

The rest seems to work but navigation (goto definition) does not.

We already checked the metals side of things: https://github.com/scalameta/metals/issues/479

### Environment

I'm using metals 0.3.3.

```
% freebsd-version -ku
11.2-RELEASE-p8
11.2-RELEASE-p8
% pkg info -E neovim
neovim-0.3.2
% pkg info | grep -i ^gtk
gtk12-1.2.10_27                Gimp Toolkit for X11 GUI (previous stable version)
gtk2-2.24.32                   Gimp Toolkit for X11 GUI (previous stable version)
gtk3-3.22.30_4                 Gimp Toolkit for X11 GUI (current stable version)
```

**Comment by olafurpg** [comment]
@jan0sch thanks for reporting! I believe this is a metals issue and not related to vim-lsc.

**Comment by jan0sch** [comment]
Okay, I'll check there. :)

**Comment by olafurpg** [comment]
You can close this issue, I'm not sure it can be fixed here.
