### ISSUE TITLE
vim-lsc does not work with neovim 

### ISSUE THREAD

**Issue by tdgs** [natebosch/vim-lsc#147]
Hey,

I am not a vim script expert or anything, but I think this line here https://github.com/natebosch/vim-lsc/commit/20a3545fb0b6551349ecd55c8fd0402bcebc3ab5#diff-ba760fb312e0b5ab929d6b8838ae01dcR63
 broke support for neovim, because the `v:none` variable is not supported: https://github.com/neovim/neovim/blob/master/runtime/doc/vim_diff.txt#L252

Unfortunately my vim-foo is not strong enough to fix this or to understand what is happening, but I hope this issue helps

**Comment by ckipp01** [comment]
Just took a look at this as I'm having the same issue. @tdgs I came to the same conclusion as you, and it looks like that line introduced this error. I can't actually find any information on `v:none`.
