### ISSUE TITLE
error messages at end of line dont show up

### ISSUE THREAD

**Issue by Alexmac22347** [natebosch/vim-lsc#157]
Hi, this is a fairly minor bug, but when there is an error which occurs at the end of the line, it doesn't get highlighted. I can make the error show up by adding a space at the end of the line, which will then be highlighted in red. 

![screenshot_2019-02-01_20-11-13](https://user-images.githubusercontent.com/14203288/52119886-fa9e4080-265d-11e9-8413-f3d302bd194d.png)
![screenshot_2019-02-01_20-11-20](https://user-images.githubusercontent.com/14203288/52119887-fa9e4080-265d-11e9-8b8a-66cd1415fe85.png)

**Comment by natebosch** [comment]
I'm not sure what the best thing to do here would be. `matchaddpos` won't let me highlight something past the end of the line.

If you use `set list` and `set listchars=eol:$` then this would show up, but that has a drastic impact on UX.

With nvim I could maybe do something with `nvim_buf_set_virtual_text` but I'd likely need to look for this case specifically and it could be error prone.

Would it work for you to start the highlight one character earlier? It might look a bit strange in the case where it highlights the last character of a word...

**Comment by andymass** [comment]
@natebosch, `matchadd('lscDiagnosticError', '$')` will actually highlight the EOL

**Comment by natebosch** [comment]
I need to do some testing, but I'm hoping that #196 will fix this.
