### ISSUE TITLE
E13: File exists (add ! to override) when saving a file since latest version of this plugin

### ISSUE THREAD

**Issue by softinio** [natebosch/vim-lsc#158]
Since updating my plugins I get this error: 
`E13: File exists (add ! to override)`

Everytime I try to save a file even though nothing else has changed that file.

This started happening after I updated to the latest of this plugin. I have confirmed vim-lsc cause by removing it and problem went away. As an additional verification I did same on a second machine and experienced same (macos and Linux).

**Comment by natebosch** [comment]
Have you noticed any particular behaviors that lead to this? For instance does it only happen after you jump to a definition that takes you to another file?

Maybe something is behaving poorly after we started using `fnameescape`? (though that really seems like the right thing to do)

https://github.com/natebosch/vim-lsc/commit/20a3545fb0b6551349ecd55c8fd0402bcebc3ab5#diff-d75f72ad119ad344b6a3170da49be1d9R107

Or maybe some bug was introduced here?
https://github.com/natebosch/vim-lsc/commit/b8a04ab0721c7383290ee997dd3bd491b8f5f93c

Can you try syncing to 77fa2fa5f2ba33c2b7ce8641125236e10b770124 or to c6d088d86cf485567cdafcf451c8b265b1620efe and see if things work at either of those commits?

Are you on vim or neovim?

**Comment by softinio** [comment]
@natebosch  Hey I pulled the latest from your master and problem went away and all working: 

https://via.softinio.com/Screen-Shot-2019-02-08-08-45-54.png

Feel free to close this. 

Before I did this it would literally happen on editing any file. 

I use neovim.

Thanks as always for this great plugin.

**Comment by natebosch** [comment]
Glad to hear it's working 😄
