### ISSUE TITLE
Don't send textDocument/didSave unless server advertises support for it

### ISSUE THREAD

**Issue by DanTup** [natebosch/vim-lsc#164]
I think the comment about didSave being sent unconditionally in #114 is incorrect. In the spec the `ServerCapabilities` has:

```ts
/**
 * Defines how text documents are synced. Is either a detailed structure defining each notification or
 * for backwards compatibility the TextDocumentSyncKind number. If omitted it defaults to `TextDocumentSyncKind.None`.
 */
textDocumentSync?: TextDocumentSyncOptions | number;
```

My interpretation is that `textDocument/didSave` should not be sent if `textDocumentSync` is `1`, `2` or an object with `.save == true`. In Dart [we're sending](https://github.com/dart-lang/sdk/blob/15f1fc212c609785950af084cf82197cb7d2cb70/pkg/analysis_server/lib/src/lsp/handlers/handler_initialize.dart#L62) an object (`TextDocumentSyncOptions`) with `save` set to false.

**Comment by natebosch** [comment]
The `save` field should be a `SaveOptions` instance, which has a single boolean field `includeText`.

My impression is that the `didSave` request should be sent unconditionally, but that the server can indicate whether it wants the text included.

We _could_ only send `didSave` notifications if the `save` field is a non-null dict, regardless of the value of `includeText`, but I'm worried it would be breaking and I can't tell from the spec whether that would be correct.

**Comment by natebosch** [comment]
Here's an issue discussing this:
https://github.com/Microsoft/language-server-protocol/issues/288

I think what you want to do in the server is send a dict _without_ the `save` key, and I can interpret the missing key as "don't send".

**Comment by DanTup** [comment]
Sorry, I made a mistake reading what we sent above where I mentioned a boolean (I read the `willSave` field). We are actually already not sending `save`:

```dart
new TextDocumentSyncOptions(
          true,
          TextDocumentSyncKind.Incremental,
          false,
          false,
          null,
        )
```

```js
"textDocumentSync": {
	"openClose":  true,
	"change":  2,
	"willSave":  false,
	"willSaveWaitUntil": false
}
```

**Comment by natebosch** [comment]
Sounds good, this client doesn't support `willSave` so I'll see about disabling the `didSave` in the case where the `save` field is omitted.
