### ISSUE TITLE
Error in lsc#edit#rename - Unknown function: trim

### ISSUE THREAD

**Issue by acetylen** [natebosch/vim-lsc#168]
**Editor version:** Neovim 0.3.1-1
**vim-lsc version:** 16f4f99

## Minimal example
(Tested with [palantir/python-language-server](http://github.com/palantir/python-language-server))

```python
abc = 123
```
## Actions
1. Position cursor on `abc`
2. `:LSClientRename`
3. Enter new name

## Expected result

Variable `abc` changes name.

## Actual result
```
Error detected while processing function lsc#edit#rename:
line    7:
E117: Unknown function: trim
E116: Invalid arguments for function empty
E15: Invalid expression: (empty(trim(new_name)))
```

**Comment by natebosch** [comment]
hmm, I didn't think `trim()` was very new, and it exists for me in `0.3.3`.

Does `:help trim()` show anything?

I can easily replace this usage with a regex so I'll go ahead and do that - but I'm not sure if it's feasible to never use `trim()`...

**Comment by acetylen** [comment]
Trim does not appear to be in neovim 0.3.1, no. I agree that builtins should be preferred, but 0.3.1 is still the default version for many package managers.
