### ISSUE TITLE
What unicode unit does vim-lsc use in lsp ranges?

### ISSUE THREAD

**Issue by Avi-D-coder** [natebosch/vim-lsc#170]
Does this project use UTF-8, UTF-16, codepoint, or grapheme cluster indexes for lsp ranges?

If this project uses a unit other than UTF-16 could/would you ever conform to the protocol 3.0 and use UTF-16?

I am conducting a [survey](https://github.com/Avi-D-coder/lsp-range-unit-survey) to inform the debate over what unit ranges should use in the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol).
The debate is occuring in [issue #376](https://github.com/Microsoft/language-server-protocol/issues/376).

**Comment by natebosch** [comment]
This project currently uses whatever `strchars()` uses (though there are probably also bugs). I'm pretty sure that is codepoints.


I do plan on conforming to spec to use UTF-16.

**Comment by Avi-D-coder** [comment]
@natebosch thanks

**Comment by andymass** [comment]
I think if vim-lsc were to become utf-16 conforming, where `col('.')` (byte position) is used would be replaced with something like;

```vim
" get column number measured in utf16 code units (a𐐀b -> [0, 1, 3])
function! Utf16col()
  if col('.') == 1
    return 0
  endif
  let str = getline('.')[:col('.')-2]   " chars prior to cursor
  return strlen(substitute(str, '.',
        \ '\=char2nr(submatch(0)) >= 0x10000 ? "XX" : "X"', 'g'))
endfunction
```

Not clear what to do at the moment since servers are inconsistent.
