### ISSUE TITLE
Jump to error

### ISSUE THREAD

**Issue by timtraversy** [natebosch/vim-lsc#181]
Is jump to error implemented somewhere in here? Like a shortcut that jumps to the next line that has an error. Happy to take a shot at, just wanted to check if I was missing it.

**Comment by natebosch** [comment]
Nothing currently exists. We always populate the location list and my current workflow is to open that up and jump to errors that way.

My idea solution for this would be to, if possible, smartly update the index into the location list every time we change the errors such that we can use `:lnext` and `:lprev` for this use case. I'd hope to avoid needing some kind of custom thing for this like `:LSClientNextError`...
