### ISSUE TITLE
How to send configuration for lsp server?

### ISSUE THREAD

**Issue by sivakov512** [natebosch/vim-lsc#182]
Hi!
Thank you for awesome plugin, it is realy cool and I like it

Please help me - how to send configuration for lsp server? For example I want to disable `yapf` plugin in `pyls`. Previously I did it like this vith `vim-lsp`
```vim
au User lsp_setup call lsp#register_server({
    \ 'name': 'pyls',
    \ 'cmd': {server_info->['pyls']},
    \ 'whitelist': ['python'],
    \ 'workspace_config': {'pyls': {'plugins': {
        \'jedi_completion': {'include_params': v:false},
        \'jedi_definition': {'follow_imports': v:true},
        \'mccabe': {'enabled': v:false},
        \'pycodestyle': {'enabled': v:false},
        \'pydocstyle': {'enabled': v:false},
        \'pyflakes': {'enabled': v:false},
        \'yapf': {'enabled': v:false},
    \}}},
 \ })

```

Can you provide an example?

**Comment by natebosch** [comment]
I'm not familiar with the concept of `workspace_config` - do you know what this translates to in LSP?

Maybe it ends up as - https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration

I don't have support for that today but I can definitely take a look at adding it...

Do you have an example of the requests that are sent to the server based on this config?

**Comment by sivakov512** [comment]
Yes, I think it is `workspace_didChangeConfiguration`. Sorry, I have no example of the request (

**Comment by sivakov512** [comment]
@natebosch is this feature planned? =)

**Comment by natebosch** [comment]
The main thing I need to figure out is whether that `pyls` key is intended to be sent within the settings to the server (which doesn't make much sense to me), or whether that is an artifact of trying to duplicate some configuration approach from VSCode...

**Comment by natebosch** [comment]
As far as I can tell the `vim-lsp` implementation would keep that key.

https://github.com/prabirshrestha/vim-lsp/blob/6de0ccd6fb2f415f242d8e77bf689cb736f6304c/autoload/lsp.vim#L452-L457

**Comment by natebosch** [comment]
@sivakov512 can you try the branch in https://github.com/natebosch/vim-lsc/pull/199 and see if it works for you?

I think that you should be able to use the same config you would in `vim-lsp` if that was working. I'm not entirely sure about the structure of the keys that `pyls` is expecting - whether they want that top level `pyls` key or not, so you might need to play around with it a bit.

**Comment by natebosch** [comment]
Some relevant discussion about how that `pyls` key might be intended to work: https://github.com/natebosch/vim-lsc/issues/132#issuecomment-453468122

**Comment by sivakov512** [comment]
Thank you!
I test it with python only, looks like it works

**Comment by natebosch** [comment]
Thanks for the confirmation - merged to master
