### ISSUE TITLE
Invalid completions for first chars on line

### ISSUE THREAD

**Issue by sivakov512** [natebosch/vim-lsc#183]
When triggering completion manually for partialy typed first word on line it may produce invalid results.
For example I trigger completion after `imp` on these screenshot
![image](https://user-images.githubusercontent.com/10251687/57298116-0e809500-70da-11e9-9335-e29214cf56fb.png)

But all works well if I do the same thing after some spaces (triggered after `imp` also)
![image](https://user-images.githubusercontent.com/10251687/57298183-3ff96080-70da-11e9-9b7a-edb9563ae657.png)

**Comment by natebosch** [comment]
I'm unable to repro this. What commit sha are you synced to?

**Comment by sivakov512** [comment]
I update my plugins everyday, so I use latest version from master. Looks like this is `1fb7e1a50a11f5c45988c6515141b83e131d674f` now.

**Comment by rliang** [comment]
Can also confirm.

**Comment by sivakov512** [comment]
Any news here?

**Comment by natebosch** [comment]
What version of vim are you using? Given that we also see some behavior differences in #184 I wonder if maybe the way `completefunc` and `omnifunc` were handled in older versions of vim is coming in to play here.

**Comment by natebosch** [comment]
Do you see different behavior if you enable autocomplete and let it trigger that way by typing 3 characters?

**Comment by sivakov512** [comment]
> What version of vim are you using?

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 28 2019 09:06:19)
Included patches: 1-1764
Compiled by void-buildslave@a-hel-fi
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       +X11
+diff              +modify_fname      -sound             +xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        -mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: cc -c -I. -Iproto -DHAVE_CONFIG_H     -fstack-clash-protection -mtune=generic -O2 -pipe   -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: cc   -L. -Wl,-z,relro -Wl,-z,now     -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now     -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lelf -lnsl   -lncursesw -lacl -lattr -ldl  -L/usr/lib -llua -Wl,-E -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -pthread  -L/usr/lib/perl5/core_perl/CORE -lperl -lm -lcrypt -lpthread -ldl  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm  -lruby -lm
```

> Do you see different behavior if you enable autocomplete and let it trigger that way by typing 3 characters?

I don't see any completion when typing at start of line

**Comment by sivakov512** [comment]
Any news here?

**Comment by natebosch** [comment]
I still haven't been able to repro this. I installed vim at the same patch level and when I manually complete at the beginning of the line I don't see the same problem.

I don't know what could happen that would make the `omnifunc` get treated differently for you than for me. I wouldn't expect that another plug should be able to interfere, but maybe it's possible.

Could you try removing the `ale` plugin and see if that makes any difference?

Also, can you check what `:set completeopt` and `:set omnifunc` show for the buffer when you see this happen?

**Comment by natebosch** [comment]
Looking at the code a bit I do have a pretty clear bug when the completion items don't give me a way to find the start column for the completion...

https://github.com/natebosch/vim-lsc/blob/df82cce97ae3eb30a2282915a07b41873039e8fe/autoload/lsc/complete.vim#L195

That should be `return 1`. I can reproduce the behavior if I avoid using the completion item text edits to find the start column.

**Comment by sivakov512** [comment]
Cool! Thank you!
