### ISSUE TITLE
Error message when the build server prompts for input

### ISSUE THREAD

**Issue by NightWhistler** [natebosch/vim-lsc#188]
I'm using Metals as my language server, and when you first open a Scala file it prompts to ask what it should do.

This now leads to an error message, and I am unable to select any of the options:
![Screenshot from 2019-05-29 11-33-24](https://user-images.githubusercontent.com/1177235/58546425-99e6d500-8205-11e9-8c2d-b5a5c612bd19.png)

Vim version is neovim 0.3.1

**Comment by natebosch** [comment]
Ah, I don't have a server which uses this code path but I think I see the problem. Can you try https://github.com/natebosch/vim-lsc/pull/189 and see if it fixes it for you?

I'll see if I can get a server installed that uses `showMessageRequest` to validate.

**Comment by natebosch** [comment]
I did a little manual testing and I'm pretty confident with the fix so I've merged it. Please let me know if updating to the latest does not solve this for you.

**Comment by NightWhistler** [comment]
Awesome, and thank you! It might take me a few days before I get a chance to check it, but I'll update you when I do.
