### ISSUE TITLE
Small hidden bug in a getbufinfo() call

### ISSUE THREAD

**Issue by bfrg** [natebosch/vim-lsc#197]
There's a small typo in a `getbufinfo()` call in [plugin/lsc.vim](https://github.com/natebosch/vim-lsc/blob/e0556e00e6d36537084c36f9b31c4b26a1c029ca/plugin/lsc.vim#L60). `getbufinfo()` doesn't accept the key `loaded`. This should probably be `bufloaded`:
```diff
diff --git a/plugin/lsc.vim b/plugin/lsc.vim
index 14020df..1027b2d 100644
--- a/plugin/lsc.vim
+++ b/plugin/lsc.vim
@@ -57,7 +57,7 @@ endfunction
 " restarted the next time a window or tab is entered with this file type.
 function! RegisterLanguageServer(filetype, config) abort
   call lsc#server#register(a:filetype, a:config)
-  for buffer in getbufinfo({'loaded': v:true})
+  for buffer in getbufinfo({'bufloaded': v:true})
     if getbufvar(buffer.bufnr, '&filetype') == a:filetype
       call lsc#server#start(a:filetype)
       return
```
- `getbufinfo({'bufloaded': 1})` returns buffer information of loaded buffers only
- `getbufinfo({'loaded': 1})` returns buffer information of all buffers, including unloaded ones just like `getbufinfo()`. It seems that the function silently ignore dictionaries with unsupported keys.

**Comment by natebosch** [comment]
Thanks!
