### ISSUE TITLE
SignatureHelp is broken

### ISSUE THREAD

**Issue by Tinee** [natebosch/vim-lsc#208]
When going to a function signature and press `gm` I get an error.

**Information**:
- Language: Go
- Vim version: 8.1.1850

**Expected**
The preview window to fill out the function signature

**Actual**
`[lsc:Error] Error dispatching message: 'Vim(if):E735: Can only compare Dictionary with Dictionary'` 

I have located the change that caused this [here](https://github.com/natebosch/vim-lsc/commit/536c7d660c9ab9b730e3114881c03e472085f6d9#diff-eb537523d6a3e635fd24eec58067448fR20)

I have also noticed that when calling `cm` on a function signature that doesn't have any parameters it returns an error. (see picture below)

<img width="129" alt="Screen Shot 2019-08-22 at 16 58 21" src="https://user-images.githubusercontent.com/16955389/63487117-27347f80-c4fe-11e9-82a0-9d8d8c4ae995.png">

**Expected**
Not sure what do expect in this scenario, but I assume it would just print out the signature into the preview window.

**Actual**
`[lsc:Error] Error dispatching message: 'Vim(if):E716: Key not present in Dictionary: parameters) && has_key(signature.parameters[active_parameter], ''l
abel'')'
`

**Comment by natebosch** [comment]
Fixed by #209

Thanks!
