### ISSUE TITLE
wrong view when doing jump to definition on an already opened file

### ISSUE THREAD

**Issue by sigmundch** [natebosch/vim-lsc#21]
How to repro:
* open b.dart
* put cursor under `A`
* jump to definition -> works great!
* go back (`C-O`)
* jump to definition -> cursor is in the right position of the window, but the text is not scrolled to the right place

**b.dart**:
```dart
import 'a.dart';
class B extends A {}
```

**a.dart**:
```dart
// Note: all these empty lines are on purpose to cause the definition to be further out from the window size














































































class A {}
```

**Comment by natebosch** [comment]
We tracked down that the ruler is showing the cursor being in the right place but the screen just doesn't show the right stuff. I can't repro myself but `redraw` seems to fix it so that's easy enough and won't hurt any cases that aren't seeing this issue.
