### ISSUE TITLE
Blog post: LSP in Vim with the LSC Plugin

### ISSUE THREAD

**Issue by bluz71** [natebosch/vim-lsc#215]
Hello Nate,

You may be interested in [this blog I wrote about LSP and the LSC plugin](https://bluz71.github.io/2019/10/16/lsp-in-vim-with-the-lsc-plugin.html).

**Comment by natebosch** [comment]
Really cool! Thanks for sharing!

One note:

> `autocmd FileType ruby,javascript setlocal omnifunc=lsc#complete#complete`

You can accomplish the same by adding `'Completion': 'omnifunc'` to your `g:lsc_auto_map` dict.

```viml
let g:lsc_auto_map = {
 \  'GoToDefinition': 'gd',
 \  'FindReferences': 'gr',
 \  'Rename': 'gR',
 \  'ShowHover': 'K',
 \  'Completion': 'omnifunc',
 \}
```

**Comment by bluz71** [comment]
That is elegant.

Question, that will only set the omnifunc for the file types specified with a language server? I suspect so, which is what we want.

If so, I will update the post.

**Comment by natebosch** [comment]
> Question, that will only set the omnifunc for the file types specified with a language server?

Yup 😄

**Comment by bluz71** [comment]
Excellent. Will update soon.
