### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by habamax** [natebosch/vim-lsc#216]
Hi, 

OS: win10
vim: 8.1.2151

I have the following setup (python lang server is installed):
```
" pip install 'python-language-server[all]'
let g:lsc_auto_map = v:true
let g:lsc_server_commands = { 
			\'python' : 'pyls',
\}
```

Then I have the a file in `~/projects/test.py`, just a hello world.

## Open this file in gVim `:e ~/projects/test.py`
![image](https://user-images.githubusercontent.com/234774/66901809-1ab53a80-f008-11e9-9f51-b156a0942e35.png)

![image](https://user-images.githubusercontent.com/234774/66901859-2e60a100-f008-11e9-92e9-0a632987d90b.png)

While exiting after that I get some other errors but I can't capture them.

Then if I change current directory to `~/projects` it seems that something works. For example, `K`  gives me documentation. Some other mappings also works (`gd`, `Ctrl-]`):

![image](https://user-images.githubusercontent.com/234774/66902109-c494c700-f008-11e9-9ef1-d9ef4a2702a2.png)

Not sure if it is intended behavior or not.

## cmd vim directly from `~/projects`
`cd ~/projects`
`vim test.py`

No errors are shown at first. But after a couple of seconds there is:

![image](https://user-images.githubusercontent.com/234774/66902343-2bb27b80-f009-11e9-91f2-25b2406d054d.png)

![image](https://user-images.githubusercontent.com/234774/66902371-38cf6a80-f009-11e9-8c77-f4e2e12f8d2c.png)

And then it seems to work? (again `K` works etc)

And then you exit:
![image](https://user-images.githubusercontent.com/234774/66902468-5e5c7400-f009-11e9-93e0-0a6045144fb0.png)

**Comment by habamax** [comment]
Should I probably just set `suppress_stderr`?
It makes most of error messages gone except the one with `OSError [Errno 22]`:

![image](https://user-images.githubusercontent.com/234774/66914653-f2393a80-f01f-11e9-81c1-e67c0814e615.png)

**Comment by ainar-g** [comment]
It should probably be set to `v:true` by default. See #213.

**Comment by natebosch** [comment]
> Not sure if it is intended behavior or not.

It's not, this points to something being broken in the language server. You might want to follow up with the authors of the server for help.

> Should I probably just set `suppress_stderr`?

This will mask the issue rather than solve it - but if there aren't other negative side effects that may be ok...



> It makes most of error messages gone except the one with `OSError [Errno 22]`:

That looks scary, I wonder who is creating that bad file path. It could be a bug in the server, or a bug in this client.

**Comment by habamax** [comment]
> 
> 
> > Not sure if it is intended behavior or not.
> 
> It's not, this points to something being broken in the language server. You might want to follow up with the authors of the server for help.

Ok, clear.

> > Should I probably just set `suppress_stderr`?
> 
> This will mask the issue rather than solve it - but if there aren't other negative side effects that may be ok...

OK, clear too.

> > It makes most of error messages gone except the one with `OSError [Errno 22]`:
> 
> That looks scary, I wonder who is creating that bad file path. It could be a bug in the server, or a bug in this client.

I was under impression that the plugin itself somehow passes the current working directory to language server from vim.
But if this is not the case, that is ok.

**Comment by habamax** [comment]
![vim-lsc-error](https://user-images.githubusercontent.com/234774/66977019-c6b06180-f0ac-11e9-8b20-517999849e81.gif)

**Comment by habamax** [comment]
And actually it is

    :echo lsc#file#fullPath()

Which normalizes filepath effectively prepending getcwd() to path:
```
function! lsc#file#fullPath() abort
  let l:file_path = expand('%:p')
  if l:file_path ==# expand('%')
    " Path could not be expanded due to pointing to a non-existent directory
    let l:file_path = lsc#file#normalize(getbufinfo('%')[0].name) !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! HERE
  endif
  return l:file_path
endfunction

...

" If `buffer_name` is relative, normalize it against `cwd`.
function! lsc#file#normalize(buffer_name) abort
  if a:buffer_name[0] ==# '/' | return a:buffer_name | endif
  let l:full_path = getcwd().'/'.a:buffer_name   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! << HERE
  let s:normalized_paths[l:full_path] = a:buffer_name
  return l:full_path
endfunction


```

**Comment by habamax** [comment]
My error is gone if I always consider "buffer name is not relative".
Looks like the relative check is not cross-platform.

```
" If `buffer_name` is relative, normalize it against `cwd`.
function! lsc#file#normalize(buffer_name) abort
  return a:buffer_name " THIS
  if a:buffer_name[0] ==# '/' | return a:buffer_name | endif "!!!!!!!not sure if this absolute path check would work on Win... 
  let l:full_path = getcwd().'/'.a:buffer_name
  let s:normalized_paths[l:full_path] = a:buffer_name
  return l:full_path
endfunction

```

**Comment by habamax** [comment]
This might be a fix:

```
" If `buffer_name` is relative, normalize it against `cwd`.
function! lsc#file#normalize(buffer_name) abort
  if a:buffer_name =~ '^/\|\%([c-zC-Z]:[/\\]\)' | return a:buffer_name | endif
  let l:full_path = getcwd().'/'.a:buffer_name
  let s:normalized_paths[l:full_path] = a:buffer_name
  return l:full_path
endfunction
```

Instead of checking first char for `/` it checks if beginning is matched against `/` or windows `C:/`, `f:\` etc with `^/\|\%([c-zC-Z]:[/\\]\)`

**Comment by natebosch** [comment]
Good find! I'll take a look at the PR.

**Comment by natebosch** [comment]
Fix is merged in https://github.com/natebosch/vim-lsc/commit/5f43d085fb79346748a672115e696804d769c5ec

Thanks for the fix.
