### ISSUE TITLE
List of servers that work with vim-lsc ?

### ISSUE THREAD

**Issue by buttjake** [natebosch/vim-lsc#222]
Is there a list of language servers that are confirmed to work nice with vim-lsc ? For example I'm looking at setting up vim-lsc with ominisharp-roslyn and I can't find anything online about that.

I mean, there's this. https://github.com/natebosch/vim-lsc/wiki/Language-Servers but it doesn't really cover that many languages. ( I don't mean to sound entitled, it's just an observation, maybe I'm looking at the wrong resource )

**Comment by ainar-g** [comment]
<p>
IAN the author of the plug-in, but LSP is a protocol, so technically all
complying servers should be supported.
</p>

**Comment by natebosch** [comment]
I have intentionally avoided adding stuff that is specific to various languages so as long as the server follows the protocol well enough it should work. If you find bugs working with a particular server you can file issues and we can determine whether it's following the protocol (and we need an update in the client) or whether it's don't something outside the protocol (and we need a workaround or to follow up with the server authors). The wiki is updated by the community and is ad hoc. I haven't gone out and tried to run with every server available.

I'd recommend trying it out and sharing your experience on the wiki 😄
