### ISSUE TITLE
Enhancement suggestion: client-side prefix-based sorting option?

### ISSUE THREAD

**Issue by bluz71** [natebosch/vim-lsc#226]
Hello Nate,

I am dipping my toe into Flutter, and therefor Dart. I have the Dart LSP Analysis Server up and going.

However, the completion suggestions are often in non-friendly server-provided fuzzy order, or so it seems.

An example using the Flutter default app:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: The|
  }
}
```

Cursor is at the end of `The` marked by `|`.
Completion suggestions via LSC are: 'AnimatedTheme', 'PopupMenuTheme', etc etc.
Ideally I would like the top suggestions to match the prefix I have already typed such as: 'ThemeData', 'ThemeMode' (which are listed, but very far down the list).

In VSCode and Android Studio I get prefix sorted suggestions at the top. I suspect the sorting happens in the editor (client-side), maybe using the LSP `sortText` property (or not), I don't know. Whatever happens, it is a much better list in terms of usability.

Can LSC do similar prefix-ranking client-side?
Offer an option that sorts the suggestions based on the prefix used to gather the suggestions to begin with? Defaulting to off (current mode).
I know VimScript is slow, and sorting a long list may suck badly performance wise.

LSC aims to be minimal and fast.
Hence, this suggestion may not suit, I understand if so, just close this.

Are there any other suggestions possible? Can I tell the Dart LSP server to sort-by-prefix instead of the current fuzzy order? 

Regards.

**Comment by natebosch** [comment]
I suspect we likely can do some sorting here. We'd want to do it around here:

https://github.com/natebosch/vim-lsc/blob/730d901164497f17b15a42d531b346752cc10765/autoload/lsc/complete.vim#L129

**Comment by bluz71** [comment]
I have been thinking, simply  favouring prefix matches is all that’s wanted, not sorting. Sorting can get complicated with regard to order, locales and Unicode (we don’t want or need that).

I would like some thing like this:

```
list prefixMatches[]
list matches[]

for each completion 
  if completion starts with already typed prefix then append to prefixMatches
  else append to matches
end
return prefixMatches + matches
```

Prefix matching should be case sensitive.

Also, I appear to be the first person that has asked for this, so I suspect this probably should be behind an option that defaults to off. Note, I have a very slow Core-M MacBook, so I could test out the performance impact, heck it may be less bad than I fear.

My toying with Dart + Flutter appears to show that both Android Studio and VSCode both do this type of client side prefix-matching.

If LSC had a similar capability it would be outstanding.

**Comment by bluz71** [comment]
Hello,

This appears to be a fairly simple enhancement.

https://github.com/natebosch/vim-lsc/blob/730d901164497f17b15a42d531b346752cc10765/autoload/lsc/complete.vim#L208

Currently you do a case insensitive anywhere in string comparison, those are the completions to be displayed.

My ideal would instead be:

```viml
return match(word, '\C' . a:base) == 0
```

Only completions that case-sensitively match the base should be displayed.

I have been testing this and it satisfies the need in the first post. Works well in Dart + Flutter code.

My enhancement should not be the default, hence maybe have a new flag such as `g:prefix_matching_completions_only` defaulting to false? No, I don't love that name.

If you have some thoughts about preferred names to distinguish between current behaviour and prefix-matching-completions-only please let me know.

I can whip up a new PR tomorrow for this.

**Comment by bluz71** [comment]
I am very pleased with this enhancement.
Autocompletions feel more natural and useful now, especially with the Dart language server.
Thanks.
