### ISSUE TITLE
Support renaming import prefixes

### ISSUE THREAD

**Issue by leonsenft** [natebosch/vim-lsc#230]
Attempting to rename an import prefix in Dart code (using `dart_language_server`) doesn't work, in different ways depending on whether the cursor is on the prefix definition or use.

```dart
import 'self.template.dart' as template;
                     // Case 1 ^^^^^^^^

void main() {
  NgTestBed.forComponent(template.TestComponentNgFactory);
               // Case 2 ^^^^^^^^
}
```

**Case 1:** With the cursor on the import prefix definition, renaming it (`gR`) works on the definition, but doesn't change any of the usages in the file.

**Case 2:** With the cursor on the import prefix use, renaming it (`gR`) fails with the following error:

> [lsc:Error] The getter 'edits' was called on null.^@Receiver: null^@Tried calling: edits

**Comment by natebosch** [comment]
I can't repro using the analysis server. If you are are still using `dart_language_server` I'd highly recommend migrating. https://github.com/natebosch/vim-lsc-dart will help you automatically configure this client to talk to the analysis server.

We can reopen if you are able to repro with the analysis server.

**Comment by leonsenft** [comment]
Oh, I wasn't aware `dart_language_server` had been succeeded. It works as expected with `vim-lsc-dart`.
