### ISSUE TITLE
Mute unhandled notifications

### ISSUE THREAD

**Issue by pwntester** [natebosch/vim-lsc#234]
https://github.com/natebosch/vim-lsc/blob/d6bb42bf75bd5dfd28b1f3216749475f940abc5b/autoload/lsc/server.vim#L331-L333

This gets very noisy on some servers. For example java one sends a lot of looong `language/status` responses that get echoed here. 

I have enabled a new option to disabled them in a local branch, but thinking about it, it seems like a debug leftover to me, so maybe solution is not to add a new option to mute them, but to actually remove this code, and maybe let it handled by the previous else branch where users can handle them with a custom callback

Thanks,
a

**Comment by natebosch** [comment]
I've always been a little paranoid about hiding stuff from the server that might make it easier to understand why other stuff may be behaving in a certain way - but between this, noisy stderr, and noisy `window/logMessages` I think most server authors have a different viewpoint than I do about how these things should be used.. I also think I've been using it as an excuse to avoid properly implementing some kind of diagnostic tool that could expose these things when you ask for them without spamming them by default...

I agree that it would be best to suppress this. I won't block it on getting a better recording and diagnostic tool for when we want to go looking for them.
