### ISSUE TITLE
LSClientFindImplementations throws

### ISSUE THREAD

**Issue by leonsenft** [natebosch/vim-lsc#235]
With the cursor on an abstract method (in Dart), `:LSClientFindImplementations` throws the following error:

[lsc:Error] Error dispatching message: 'Vim(if):E716: Key not present in Dictionary: type != a:i2.type'

**Comment by natebosch** [comment]
Interesting, in order to hit this we'd need to have 2 implementations reported at exactly the same place. I think it's clear what the bug is though, so I can fix it.
