### ISSUE TITLE
Intermittent error 'Checker' object has no attribute 'NAMEDEXPR'^@

### ISSUE THREAD

**Issue by petri-dev** [natebosch/vim-lsc#261]
Hello,

I've recently been using vim-lsc and finding it great. I do, however, get an intermittent error:
[lsc:Error] StErr from pyls: 'Checker' object has no attribute 'NAMEDEXPR'^@
I'm not sure if this is the correct place to report it since it may be an issue with the pyls server - however I thought best to start here. I'd like to give some log information, and I've set lsc_trace_level to messages, but I can't actually see where the log file is being generated. I've attached my pyls log in case that's useful. Please let me know if I can give any further info.
[lsc_log_file.txt](https://github.com/natebosch/vim-lsc/files/4178518/lsc_log_file.txt)

**Comment by natebosch** [comment]
Your language server is emitting on stderr. Usually that's a bug in the server. You might want to file an issue there.

This looks really similar to https://github.com/PyCQA/pyflakes/pull/80 for instance.

I don't think there is much we can do on the client side. If you'd like to just hide the message you see `:help lsc-server-suppress_stderr`
