### ISSUE TITLE
Handle the Shutdown sequence according to the new 3.15 specification

### ISSUE THREAD

**Issue by bfolkens** [natebosch/vim-lsc#265]
According to the new 3.15 specification for LSP, vim-lsc should first send a `shutdown` request, accepting `null` if the request is successful, and finally send an `exit` notification to the server.

See also:

- https://microsoft.github.io/language-server-protocol/specifications/specification-current/#shutdown
- https://microsoft.github.io/language-server-protocol/specifications/specification-current/#exit
- https://github.com/elixir-lsp/elixir-ls/pull/130)
- #118

**Comment by natebosch** [comment]
I think we've been doing this for a while. 

Handled here: https://github.com/natebosch/vim-lsc/blob/62c6f6aa227b1b3ef5e7cf7df9f0a9c1d855d7fe/autoload/lsc/server.vim#L77-L88
