### ISSUE TITLE
No preview window for autocomplete

### ISSUE THREAD

**Issue by sparkcanon** [natebosch/vim-lsc#266]
Hey Nate,
Thanks for this plugin. I have an issue where I don't see a preview window show up for auto-complete. I have tried setting various options for `completeopt` also tried setting them in `g:lsc_auto_completeopt` but no success.

```
" .vimrc
set completeopt=menu,menuone,preview,noinsert 

" .vim/plugin/lsc.vim
let g:lsc_enable_autocomplete = v:false
let g:lsc_trace_level='messages'
let g:lsc_hover_popup = v:false
let g:lsc_server_commands = {
  \ 'javascript': 'typescript-language-server --stdio',
  \ 'typescript': 'typescript-language-server --stdio',
  \ 'html': 'html-languageserver --stdio',
  \ 'css': 'css-languageserver --stdio',
  \ 'vim' : {
  \   'name': 'vim-language-server',
  \   'command': 'vim-language-server --stdio',
  \      'message_hooks': {
  \          'initialize': {
  \              'initializationOptions': { 'vimruntime': $VIMRUNTIME, 'runtimepath': &rtp },
  \          },
  \      },
  \   },
  \ }

let g:lsc_auto_map = {
    \ 'GoToDefinition': ',d',
    \ 'GoToDefinitionSplit': ',v',
    \ 'FindReferences': ',r',
    \ 'NextReference': ',nr',
    \ 'PreviousReference': ',pr',
    \ 'FindImplementations': ',i',
    \ 'FindCodeActions': ',a',
    \ 'Rename': ',R',
    \ 'ShowHover': v:true,
    \ 'DocumentSymbol': ',o',
    \ 'WorkspaceSymbol': ',S',
    \ 'SignatureHelp': ',s',
    \ 'Completion': 'omnifunc',
    \}
```

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 17 2020 07:45:29)
macOS version
Included patches: 1-250
```

**Comment by natebosch** [comment]
The preview window shows the "documentation" field we get from the server. If it's not sending documentation nothing will be shown. I could try reading from the "detail" field instead, or in addition to "documentation"...

**Comment by sparkcanon** [comment]
Perhaps the `details` field could be a fallback? (Apologies not hugely familiar with the protocol, reading it now)
Note: I am having the issue with all of the servers.

**Comment by natebosch** [comment]
Can you try the branch `completion-info-detail` and see how it works for you?

https://github.com/natebosch/vim-lsc/pull/267

This will include both "detail" and "documentation", whichever exist.

**Comment by sparkcanon** [comment]
Thanks for looking into this so quickly, I tried it on vim, CSS and elm servers and I do see the preview window correctly. Although I don't see it for the javascript servers namely `javascript-typescript-langserver` and `typescript-language-server` strangely. Do you reckon something off with the javascript servers itself?

**Comment by natebosch** [comment]
I wonder if it's because those servers rely on support for `completionItem/resolve`. That appears to be the case here

https://github.com/theia-ide/typescript-language-server/blob/101dae4f7b598e9bafcaa8c316f21e57341e6350/server/src/completion.ts#L148-L153

We don't really have a good hook to resolve completion items only when they are selected. I could try eagerly resolving all completion items, but I'm a little worried about the latency. I'll have to give this some thought.

In the mean time I'll go ahead an merge #267 since it seems to help in some cases.

**Comment by sparkcanon** [comment]
Brilliant, thanks for this work. Here to help, if you need.
