### ISSUE TITLE
Typing delay in large files - performance

### ISSUE THREAD

**Issue by aravind2612krishna** [natebosch/vim-lsc#273]
Thank you for this plugin! It is the fastest, most clean and bug-free of the whole lot of plugins I've used.

I'd like to report a minor issue which creates lag while typing in large files (10000+ lines)
It seems the problem is with the following code. If anything can be done to optimize this, the typing experience will improve greatly, I feel. I'm attaching the profile report also. [profile.log](https://github.com/natebosch/vim-lsc/files/4556887/profile.log)
```
FUNCTION  <SNR>114_LastDifference()
    Defined: ~\.vim\plugged\vim-lsc\autoload\lsc\diff.vim:53
Called 18 times
Total time:   2.058830
 Self time:   2.058830
count  total (s)      self (s)
353232              0.394018   while i >= -1 * line_count
706446              0.863350     if a:old[i] !=# a:new[i] | break | endif
353214              0.347690     let i -= 1
353232              0.175755   endwhile
```

**Comment by natebosch** [comment]
The slow bit is scanning backwards from the end of the file to find the last character that is different between two versions of the file. The old version in kept in memory. I suspect that your changes were mostly early in the file so the most time is spent running over unchanged lines near the end.

We could consider increasing the debounce duration, or making it configurable, so that this diff happens less often - giving you more time between changes to a file before it attempts a sync.

We could also have an option for turning off sync-as-you-type entirely, though I've been a bit resistant to that in the past.

I do wonder whether there is something faster this could be doing...

**Comment by aravind2612krishna** [comment]
Thanks for taking the time to reply.
Is there an event based system, in vim or neovim, which can do a callback when lines have been modified? 
I understand this is difficult as lines can be modified even outside cursor (like during replace or macros)
A preliminary look-up tells me that TextChanged AutoCmd can be used with the marks in '[ and ']
let start = getpos("'[")[1:2]
let end = getpos("']")[1:2]
https://vi.stackexchange.com/questions/8029/from-a-textchanged-autocommand-event-how-to-get-the-range-that-has-been-changed

I'll try to see if I can hook this up and if this benefits, but my knowledge is limited and I will take some time.

**Comment by hrsh7th** [comment]
Hi, vim has `listener_add` function, neovim has `nvim_buf_attach` function.

But these functions are event-based so difficult to support old vim.

**Comment by natebosch** [comment]
> But those functions are event-based so difficult to support old vim.

Yeah that's my big concern. I'm nervous to try to support multiple approaches since it would add a lot of testing surface and test coverage is already painfully low, but if the plugin requires something as new as `listener_add` with no fallback it's going to make it impossible for a bunch of people to use.

> A preliminary look-up tells me that TextChanged AutoCmd can be used with the marks in '[ and ']

I can't remember if I already investigated these and found them to be insufficient, or if I missed them altogether... I'll try to take another look and see if they can help. Thanks for the pointer!

**Comment by prabirshrestha** [comment]
Problem with `listener_add` is that we need to manually calc byteoffset. https://github.com/vim/vim/issues/5086.

@natebosch have you thought of porting diff algorithm to lua? Based on this https://github.com/vim/vim/pull/5198#issuecomment-557398245. Lua had 2000 time perf gains compared to vimscript.
I recently sent a PR to vim to support `vim.call` and `vim.fn` which is similar to neovim. https://github.com/vim/vim/pull/6063. This should make it easy to call vim functions from lua. Neovim even goes further by adding few functions related to encoding in c and exposed via lua.

**Comment by natebosch** [comment]
> have you thought of porting diff algorithm to lua?

I'm not sure how common lua support is across installs. I typically haven't used it, but it looks like the default package for at least ubuntu supports it. I've kept to strictly vimscript to avoid compatibility issues. I'd guess lua support is at least more common that `listener_add` so far.

**Comment by natebosch** [comment]
I spent a little time looking at the `'[` marks. I think I can't rely on them because if you make multiple edits in different locations in a function, by the time the `TextChanged` autocommand runs it looks like the marks only reflect the most recent change.

**Comment by prabirshrestha** [comment]
I started porting to lua. https://github.com/prabirshrestha/vim-lsp/blob/use-lua/autoload/lsp/utils/diff.vim
Ported only `s:FirstDifference` for now. 

For me diff is a core part which needs to be in both vimscript and lua. There are others such as semantic highlighting which has even more perf impact that I may only use lua for it. https://github.com/prabirshrestha/vim-lsp/issues/633

**Comment by natebosch** [comment]
> I started porting to lua.

Looks interesting! I'll be curious to see what kind of perf impact it has after it's fully ported. I'm especially curious if the calls to things like `vim.fn.strgetchar` inside the loops are just as fast as the rest, or if there is some overhead in bridging back to vim functions that end up offsetting the performance gains.

> For me diff is a core part which needs to be in both vimscript and lua.

Yeah it could very well be that two implementations is a requirement to get performance where possible but with a slower more compatible fallback.

**Comment by prabirshrestha** [comment]
Here is profile that Justin from neovim had shown. Even with the same code lua had 2000x perf gains. Same code in vimscript took 31sec while lua took .015sec Also note that noevim uses luajit and most linux distributions ship with lua compatibility and not luajit. Even just plain lua it should still be lot faster then vimscript. This was one of the primary reason it was completely worth experimenting. 

```
foo.vim:
 let s:sum = 0
 for i in range(1, 9999999)
 let s:sum = s:sum + i
 endfor
 call append('$', s:sum)
Time: 31.611 seconds

foo.lua:
 sum = 0
 for i = 1, 9999999 do
 sum = sum + i
 end
 vim.api.nvim_call_function('append',
 {'$', tostring(sum)})
Time: 0.015 seconds
speedup: 31.611 / 0.015 = 2107
```

**Comment by natebosch** [comment]
That benchmark with the enormous gain only has a single `vim.api.nvim_call_function` at the end, whereas the diff implementation calls vim functions in a tight loop. It's plausible that calling back into native vim functions is very fast, but depending on the implementation that part could also be slow.

I _think_ the bulk of time is spent on confirming string equality though, so as long as the string equality is checked in lua without a call back into vim you'll likely see a benefit.

**Comment by natebosch** [comment]
@prabirshrestha - _huge_ thanks for the push to try this in lua.

I played around with this a bit and it looks like we can get pretty significant improvements by porting only a small chunk of the first/last difference search. The bulk of the time is going towards checking lines that are mostly identical. Once it's narrowed down to a line the rest of the time going character by character should have a relatively fixed cost (unless you are editing files with huge lines... that's probably not a use case I'll optimize for). I hope to avoid porting the rest of the diff computation to lua to keep it simple, but these small functions are pretty manageable.

@aravind2612krishna - does your vim support lua? Can you try the branch in #282 and see if it improves things enough that it feels comfortable?

**Comment by prabirshrestha** [comment]
@natebosch This is awesome. I had similar thoughts of only porting he bottleneck after you mentioned the string comparison. The perf number is significantly down so I think it is ok to not port the entire file to lua.

**Comment by aravind2612krishna** [comment]
@natebosch I tried with the branch in #282 and it improves things drastically! The difference is staggering. The plugin is so much more joyful to use. 
`   18              0.336566  <SNR>129_FirstDifference()`
`   18              0.184030  <SNR>129_LastDifference()`
The functions are very much below the hotspot.
Thanks you @prabirshrestha and @natebosch for collaborating and optimizing!
