### ISSUE TITLE
Sending didSave to a server that does not support it

### ISSUE THREAD

**Issue by tomslee** [natebosch/vim-lsc#275]
I've been experimenting with vim-lsc and the pygls language server. I get this error:

ERROR Failed to handle notification textDocument/didSave: Object....
Traceback (most recent call last):
File.... protocol.py line 272, in _get_handler
return self.fm.buildin_features[feature_name]
KeyError: 'textDocument/didSave'

I raised this as [an issue](https://github.com/openlawlibrary/pygls/issues/108) with pygls and the response was that, according to the spce, the "client should send textDocument/didSave notification only if server allowed this in its capabilities".

It looks like vim-lsc should be checking the capabilities and then sending didSave only if supported.

**Comment by natebosch** [comment]
Yup, this does look like a bug. I think these were originally sent unconditionally and then when I fixed that I didn't go far enough - it continued to send them even if the server didn't specify the `textDocumentSync` options as a dict with enough information to enable or disable the `didSave` notifications. If the server is still sending a number as the `textDocumentSync` field it should be treated as not supporting `didSave`.

**Comment by tomslee** [comment]
LSP is a step forward for editors: thanks for bringing it to vim, Nate.
