### ISSUE TITLE
E216: no such group or event: ExitPre * let g:_lsc_is_exiting = v:true

### ISSUE THREAD

**Issue by pythonwood** [natebosch/vim-lsc#276]
plugin/lsc.vim  

```
git blame plugin/lsc.vim | grep ExitPre
a24cfd0f (Nate Bosch     2020-04-30 15:57:42 -0700 110)   autocmd ExitPre * let g:_lsc_is_exiting = v:true
```

```
vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
patch: 1-1453
```

**Comment by pythonwood** [comment]
temporary solution:

cd  vim-lsc &&  git reset HEAD^ --hard    #   git reset fb8056a --hard

**Comment by bluz71** [comment]
I am also getting the same error in gVim 8.0.1453:

```
~/.vim/plugged/vim-lsc/plugin/lsc.vim:
line 110:
E216: No such group or event: ExitPre * let g:_lsc_is_exiting = v:true
```

**Comment by kr1tzy** [comment]
Any update on this? Getting the same error: 

```bash
Error detected while processing ~/.vim/plugged/vim-lsc/plugin/lsc.vim:
line  110:
E216: No such group or event: ExitPre * let g:_lsc_is_exiting = v:true
```

**Comment by natebosch** [comment]
I'm not sure which version of vim added `ExitPre`. I think it should be safe to skip this autocmd entirely if it's missing.

Can you try switching to the branch in https://github.com/natebosch/vim-lsc/pull/278 and verify if it fixes this for you?

**Comment by bluz71** [comment]
Nate,

The latest update fixes the issue for my Vim setup; Neovim was always fine.

Many thanks,

Dennis.
