### ISSUE TITLE
Notify Language Server that 'resolve' is not supported.

### ISSUE THREAD

**Issue by bluz71** [natebosch/vim-lsc#302]
Spawning a new request from #291 

> That requires support for resolving completion items 😉 This client doesn't support that, and since it doesn't advertise that support the Dart server correctly sends them with the original request.

The Dart Analysis Server may be sending a whole heap of extra data assuming LSC has resolve support, maybe.

Anything that pads out the completion blob sent from the server to the client will slow down the LSC client. We want completion data to be a small and light as possible for maximum interactive editing performance (aka avoid stutters and pauses).

Until *resolve* is supported, I suggest LSC advertise to servers that *resolve* is not wanted.

**Comment by natebosch** [comment]
Looks like the spec doesn't define a way to specify this.

I think that just means that they expect there isn't anything "essential" that is hidden behind the resolve. In any case I don't think there is action to take on this issue for now. Sounds like the Dart server is already going to be assuming support for resolve as well.

Will track any progress towards resolving completion items at https://github.com/natebosch/vim-lsc/issues/304
I'm not sure how much work it will take, or how much will be possible.

**Comment by bluz71** [comment]
Cool, I was wondering if there was a cheap optimisation to could have been done. Alas no.

All good.

Side note, too many LSP clients force resolve by default with poor results, see [here](https://github.com/haorenW1025/completion-nvim/issues/91).

Most of the time I don't want resolve, however, one rare occasions it might be nice. Hence, I favour a manual trigger (if that's even possible?). 

If LSC is to do resolve, I would recommend thought and care and a degree of user configurability (if possible). Mixing the completion popup with a secondary popup/floating window is bad, especially with Flutter docs (which can be huge). Smart use of the preview window, like double `K` hover already does, seems better especially as one takes a completion item and then continues typing, for example adding parameters, documented in the resolve window, to an auto-completed function.
