### ISSUE TITLE
Completion kind indicators, allow user definable choices?

### ISSUE THREAD

**Issue by bluz71** [natebosch/vim-lsc#308]
Hi Nate,

When the completion menu pops up sometimes there are character indicators associated with a particular completion item; LSC uses these letters: `f`, `m`, `v`, `t` and `d` as defined in `autoload/lsc/complete` / `CompletionItemKind` function.

For the longest time I never knew what `d` stood for, now I know it is the indicator for: Keyword, Unit, Value, Text and Color. 

I mostly encounter it for Keywords. I wonder if `k` would be a more appropriate letter?

Side note, Neovim LSP + completion.nvim uses full words: `Keyword`, `Method`, `Property`, `Field`, etc.

I find the single letters a little mysterious.

Thinking aloud, it would be nice if the LSC indicators were user definable, or maybe had more verbosity about them, I would probably define these choices if possible for my own use:

- function -> `[func]` (currently `f`)
- field -> `[field]` (currently `m`)
- variable -> `[var]` (currently `v`)
- class/interface/enum -> `[type]` (currently `t`)
- keyword/unit/value/text/color -> `[key]` (currently `d`)

I also wonder of more completion item kinds should be broken out, for instance the `File` kind seems useful to know about.

Let me know your thoughts, if you are amenable I may try and cook up a PR. 

Best regards.

**Comment by bluz71** [comment]
Just having a look at [vim-lsp](https://github.com/prabirshrestha/vim-lsp) and they provide a nice model that LSC could follow.

This is their default item kinds (which are displayed in the completion menu):

```viml
let s:default_completion_item_kinds = {
            \ '1': 'text',
            \ '2': 'method',
            \ '3': 'function',
            \ '4': 'constructor',
            \ '5': 'field',
            \ '6': 'variable',
            \ '7': 'class',
            \ '8': 'interface',
            \ '9': 'module',
            \ '10': 'property',
            \ '11': 'unit',
            \ '12': 'value',
            \ '13': 'enum',
            \ '14': 'keyword',
            \ '15': 'snippet',
            \ '16': 'color',
            \ '17': 'file',
            \ '18': 'reference',
            \ '19': 'folder',
            \ '20': 'enum member',
            \ '21': 'constant',
            \ '22': 'struct',
            \ '23': 'event',
            \ '24': 'operator',
            \ '25': 'type parameter',
            \ }
```

Full words are displayed, which I now feel is a better default than just using a single letter, and *vim-lsp* enumerates all available choices rather than coalescing kinds and skipping others as coded in `autoload/lsc/complete.vim`:

```viml
function! s:CompletionItemKind(completion_kind) abort
  if a:completion_kind ==  2
      \ || a:completion_kind == 3
      \ || a:completion_kind == 4
    " Method, Function, Constructor
    return 'f'
  elseif a:completion_kind == 5 " Field
    return 'm'
  elseif a:completion_kind == 6 " Variable
    return 'v'
  elseif a:completion_kind == 7
      \ || a:completion_kind == 8
      \ || a:completion_kind == 13
    " Class, Interface, Enum
    return 't'
  elseif a:completion_kind == 14
      \ || a:completion_kind == 11
      \ || a:completion_kind == 12
      \ || a:completion_kind == 1
      \ || a:completion_kind == 16
    " Keyword, Unit, Value, Text, Color
    return 'd'
  endif
  " Many kinds are unmapped
  return ''
endfunction
```

Secondly *vim-lsp* allow a user to override:

```viml
	* completion_item_kinds
	    Type: |Dict|
	    Default: |{}|

	    This allows overriding the default text mappings for completion
	    item kinds (e.g., "module", "method") per server. Useful for
	    abbreviating or removing the kind text.

	    Example: >
		'config': { 'completion_item_kinds': {'26': 'type' } }
```

If LSC used full words to describe completion kinds, which I now **strongly** advocate, I don't think the user override would be needed.

Food for thought.

It would be easy for me to do the PR if this was deemed acceptable.

P.S. This all started because I did not know what `d` completion kinds meant; and down the rabbit hole I went.

**Comment by bluz71** [comment]
This quick `CompletionItemKind` implementation, taking the values / keys from [vim-lsp](https://github.com/prabirshrestha/vim-lsp), works well:

```viml
function! s:CompletionItemKind(completion_kind) abort
  if a:completion_kind == 1
    return 'text'
  elseif a:completion_kind == 2
    return 'method'
  elseif a:completion_kind == 3
    return 'function'
  elseif a:completion_kind == 4
    return 'constructor'
  elseif a:completion_kind == 5
    return 'field'
  elseif a:completion_kind == 6
    return 'variable'
  elseif a:completion_kind == 7
    return 'class'
  elseif a:completion_kind == 8
    return 'interface'
  elseif a:completion_kind == 9
    return 'module'
  elseif a:completion_kind == 10
    return 'property'
  elseif a:completion_kind == 11
    return 'unit'
  elseif a:completion_kind == 12
    return 'value'
  elseif a:completion_kind == 13
    return 'enum'
  elseif a:completion_kind == 14
    return 'keyword'
  elseif a:completion_kind == 15
    return 'snippet'
  elseif a:completion_kind == 16
    return 'color'
  elseif a:completion_kind == 17
    return 'file'
  elseif a:completion_kind == 18
    return 'reference'
  elseif a:completion_kind == 19
    return 'folder'
  elseif a:completion_kind == 20
    return 'enum member'
  elseif a:completion_kind == 21
    return 'constant'
  elseif a:completion_kind == 22
    return 'struct'
  elseif a:completion_kind == 23
    return 'event'
  elseif a:completion_kind == 24
    return 'operator'
  elseif a:completion_kind == 25
    return 'type parameter'
  endif
endfunction
```

**Comment by natebosch** [comment]
These letters come from `:help complete-item-kind`. I agree though that the vim standard here isn't the most useful. I'll see what it looks like to use longer kinds here.

**Comment by bluz71** [comment]
Interesting, the ’d‘ choice though is confusing as heck.

I have been using the full word indicator for a few days now, and I find it genuinely a worthwhile improvement.

I will be interested in your take.

**Comment by natebosch** [comment]
Tried this out with full words and I agree that it feels more usable. I'm going to go with capitalized an camel case to match the LSP spec exactly.

**Comment by bluz71** [comment]
Just tried your update with my Ruby, JavaScript & Dart projects, and two big thumbs up.

Definitely more usable, the extra details provided are genuinely helpful.

Thanks Nate.
