### ISSUE TITLE
Trying to use VimR with Dart, getting LSC error

### ISSUE THREAD

**Issue by sollymay** [natebosch/vim-lsc#309]
Hi @natebosch, hope you are doing great!

I have been using vim-lsc for Dart on nvim and its been working fantastic on terminal. I really really thank you for all the hard work you put to get this going.

Yesterday, I wanted to test out vimR (an nvim GUI for Mac) and I'm getting the following LSC error: 
<img width="568" alt="Screen Shot 2020-07-05 at 5 50 15 PM" src="https://user-images.githubusercontent.com/6496698/86542916-fd9eff80-bee7-11ea-8321-db4a8a44fb79.png">

I can run the Dart Analysis server on nvim running on terminal no problem, however when going to vimR (I spoke to the team behind vimR and they mentioned it might be a PATH issue and that you might be able to help me understand the issue)

running directly from terminal:
<img width="1002" alt="Screen Shot 2020-07-05 at 6 16 36 PM" src="https://user-images.githubusercontent.com/6496698/86543358-aef36480-beeb-11ea-87d7-e482d7b58632.png">

running from vimR:
<img width="1392" alt="Screen Shot 2020-07-05 at 4 45 38 PM" src="https://user-images.githubusercontent.com/6496698/86543385-f5e15a00-beeb-11ea-878d-3e11acb527a0.png">

Do you have any pointers on why LSC can't run on vimR? They mentioned vimR is only a GUI and that plug ins mostly work (its been the case apart from LSC).

Thank you!

**Comment by natebosch** [comment]
Are there any other errors if you run `:messages`?

**Comment by sollymay** [comment]
When I run :messages, I get:
<img width="574" alt="Screen Shot 2020-07-05 at 7 53 30 PM" src="https://user-images.githubusercontent.com/6496698/86544977-3a272700-bef9-11ea-8ecb-a1c0602b5df1.png">

**Comment by natebosch** [comment]
Hmm, it looks like it's exiting without responding to the `initialize` request, and without outputting anything on `stderr`. I don't think it should be an issue with `$PATH` because `vim-lsc-dart` (Am I correct that you are using that plugin to configure things?) should be using a full path to the executable.

I'll try soon to install vimR and see if I can reproduce this.

**Comment by sollymay** [comment]
Yes @natebosch. I am using vim-lsc-dart to configure things.

This is an excerpt from my init.vim 

```
call plug#begin()
Plug 'dart-lang/dart-vim-plugin'
Plug 'natebosch/vim-lsc'
Plug 'natebosch/vim-lsc-dart'
call plug#end()

"Dart Stuff
let g:lsc_server_commands = {'dart': 'dart_language_server'}
let g:dart_format_on_save = 1
autocmd CompleteDone * silent! pclose
let g:lsc_auto_map = v:true
```
Everything seems to work no problem inside terminal so that's why I'm clueless

**Comment by sollymay** [comment]
Just wanted to add that I removed the 'dart' entry from lsc_server_commands as per https://github.com/natebosch/vim-lsc-dart/issues/11, but the issue persists (wanted to go through all previous issues and see if there was any correlation with this)

**Comment by natebosch** [comment]
So when I try this launching from finder I get

> ``Could not find a `dart` executable``

This is the error I would expect if `$PATH` was to blame for the problem. If I launch the app from the terminal where I have a correctly configured `$PATH` I don't have any trouble running the analysis server...

What do you see if you are in vimR with a Dart file open and run:

```
:echo lsc#server#current()[0].config.command
```

**Comment by sollymay** [comment]
boom @natebosch, I found the issue by using that command. 

I had a really old Dart installation from brew (that I don't even remembering installing), but as soon as I removed it, vimR and lsc started working! 

Thank you for your help!

I'm gonna close this issue now.

**Comment by natebosch** [comment]
Awesome!

I think I'll look at adding the command that it tried to run to the error message when the server fails to start since it's not at all easy to find otherwise and in this case looks like it would have made it way easier to diagnose.
