### ISSUE TITLE
consider truncating reported errors

### ISSUE THREAD

**Issue by sigmundch** [natebosch/vim-lsc#31]
I've noticed that my editor slows down dramatically on some scenarios. I believe this is because of the volume of errors I am getting, but I'm not 100% sure.

Sample scenario: open `pkg/compiler/lib/src/deferred_load.dart`, jump to `_mapDependencies`, add a function right above it, but do not close the parenthesis of the argument list:
``` dart
void _newMethod(
```

This causes a bunch of cascade errors (about 400 errors?) and the editor slows down dramatically.

**Comment by natebosch** [comment]
Interesting - it could be the `matchadd` matches. I'll play around with cutting those off at a certain number. Hopefully the location list could still show them all.

**Comment by natebosch** [comment]
Ah I think I have an idea of what's going on here.

Whenever we get diagnostics for any file we try to update displayed diagnostics for everything showing. I think what might be happening is we have a couple hundred diagnostics to show, and we try to re-create them dozens of times because the analysis server is sending errors for dozens of files.

I think what needs to happen is to get smarter about when to invalidate the diagnostics for a window.

**Comment by natebosch** [comment]
Ok, I *think* the number of matches isn't a problem here. Once things settle the performance seems to be OK. I can move around the file with 243 errors in my location list (should be 243 `matchadd`s) without noticing any lag - do you see the same thing? Is it just an initial slowdown then performance is OK after it settles?

Avoiding clearing and recreating the matches does seem to help - but when we get errors for a bunch of files in a row it does still freeze up for a bit. I might be able to find other was to optimize this case.

**Comment by natebosch** [comment]
Update to the latest and see if the performance feels better. If there is still lag, especially if the lag continues after errors have had a chance to settle, please reopen the issue.

**Comment by Piping** [comment]
when the stderr keeps pop out, even thtough i set suppress stderr to true, the editor still freeze.
I have to ctrl-c to stop the process.

**Comment by natebosch** [comment]
@Piping - sounds like something different than what was reported - can you file a new issue with reproduction steps? I wouldn't expect stderr from the language server to cause vim to freeze.
