### ISSUE TITLE
LSClientRename with python-language-server duplicates the last line.

### ISSUE THREAD

**Issue by jerri** [natebosch/vim-lsc#317]
I am not sure if this is vim-lsc or pyls fault. Lets take this example file:

~~~
#!/usr/bin/env python3
# coding=utf-8


def test_me_somehow(input):
    print(input)


test_me_somehow("Hello world")

print("This should work as expected.")
~~~

If I put the cursor on `test_me_somehow` and then do `:LSClientRename "test_me"`, I get the following result:

~~~
#!/usr/bin/env python3
# coding=utf-8


def test_me(input):
    print(input)


test_me("Hello world")

print("This should work as expected.")print("This should work as expected.")
~~~

The last line somehow gets duplicated and attached to the old line. I wasn't able to check with another language server yet, as all others I currently have installed don't support rename. Can someone verify if this is just a problem on my side, or if this is actually a bug in either vim-lsc or pyls?

I am using the current version of vim-lsc (installed via vim-plug) and pyls (installed via `pip install python-language-server`).

**Comment by natebosch** [comment]
Looks like a bug in this client when applying an edit when the edit goes past the last line of the file since the edit approach depends on being able to put the cursor on the end of the range. I'll see if I can figure out a fix.

**Comment by jerri** [comment]
The problem still seems to be around. Is there anything I can do, to help? I would try to fix it myself, but I have to admit, I am not sure where to start.

**Comment by jerri** [comment]
I dove into the code and hopefully found a usable resolution. There might be better approaches. But my vimscript fu is not that deep.

**Comment by jerri** [comment]
Not a good solution?
