### ISSUE TITLE
File content gets sent with a missing trailing newline

### ISSUE THREAD

**Issue by natebosch** [natebosch/vim-lsc#318]
If the file ends with a newline `join(getbufline('%', 1, '$'), "\n")` will _not_ include it, so the language server will have an incorrect view of the file content and may report erroneous diagnostics.

**Comment by a-vrma** [comment]
Yeah this a problem with `clangd`, every file has a

    No newline at end of file (fix available) [-Wnewline-eof]

at the bottom.
