### ISSUE TITLE
The plugin has stopped working due to recent commits

### ISSUE THREAD

**Issue by Cauryl** [natebosch/vim-lsc#324]
Hi !

It seems that the plugin has stopped working due to recent commits. 

I use Vim 8.1 and the native plugin manager.
As soon as I try to use the plugin, either with omnifunc or with autocomplete, Vim displays error messages..

If I use the up-to-date plugin:

	mkdir -p ~/.vim/pack/lsp/start && cd $_
	git clone https://github.com/natebosch/vim-lsc.git

It's not working anymore.

But if I use the latest published version:

	mkdir -p ~/.vim/pack/lsp/start && cd $_
	wget https://github.com/natebosch/vim-lsc/archive/v0.3.1.tar.gz
	tar xvf v0.3.1.tar.gz

It works fine.

**Comment by natebosch** [comment]
What are the error messages?

**Comment by Cauryl** [comment]
The problem is that it is not the plugin that returns an error but Vim itself. So the messages are displayed according to my locale, i.e. in french.

However, it is not when I open Vim that the problem occurs but when I try to use the Omnicompletion with <C-X><C-O>.

The messages say that the indicated functions have not received enough arguments or are invalid.

![scrot](https://user-images.githubusercontent.com/58689680/91544172-a6357280-e91f-11ea-83ff-a8852a115406.png)

**Comment by Cauryl** [comment]
It looks like this issue: #326.

**Comment by natebosch** [comment]
Yeah, this looks like the same thing. Should be fixed now on master.
