### ISSUE TITLE
Errors that occurred during auto-completion

### ISSUE THREAD

**Issue by luocm-git** [natebosch/vim-lsc#326]
OS : ubuntu bionic(x86_64)
Editor: vim 8.0
Programing Language: dart 2.9.1

```dart
void main() {
  var time = DateTime;
  time.
}
```

_> _Error detected while processing function <SNR>14_IfEnabled[3]..lsc#complete#textChanged[5]..<SNR>48_typedCharacter[2]..<SNR>48_startCompletion:
line    6:
E119: Not enough arguments for function: bufnr
Press ENTER or type command to continue__

**Comment by natebosch** [comment]
Fixed by your PR, I forgot to restore the syntax that would let github autoclose... https://github.com/natebosch/vim-lsc/pull/327

Thanks!
