### ISSUE TITLE
Possible to change the highlight color?

### ISSUE THREAD

**Issue by dm3** [natebosch/vim-lsc#330]
I'm using the zenburn color scheme on dark background (OSX, iTerm) and the `vim-lsc` provided highlighting conflicts with the color of text which makes the text unreadable. I've searched through documentation and code but couldn't understand how to fix this.

Is it possible to make highlighting use a different color? How would I go about doing that?

**Comment by natebosch** [comment]
See `:help lsc-configure-highlight`.

The colors used by the plugin are linked to some default highlight groups (which we typically expect to be readable in any colorscheme). You can either change those built in highlight groups to different colors, or you can set the LSC specific highlight groups (listed in the help section) to any color configuration you like.

See `:help highlight` for full documentation on how to set colors in vim highlight groups.

**Comment by dm3** [comment]
thanks!
