### ISSUE TITLE
Multiple filetypes same server commands

### ISSUE THREAD

**Issue by motorto** [natebosch/vim-lsc#331]
Is it possible to give several filetypes on the same line of g:letservercommands ? 

What I mean is,instead of doing this:
```
let g:lsc_server_commands = {
                       \ 'cpp': {
			\		'command': 'clangd',
			\		'log_level': -1,
			\		'suppress_stderr': v:true,
			\  }
			\}
			\'c': {
			\		'command': 'clangd',
			\		'log_level': -1,
			\		'suppress_stderr': v:true,
			\  }
			\}
```
And having to copy and paste the same lines just changing the filetype, is it possible to do something along this type 'cpp','c': ?

I already tried with ',' and  ';' but it doesn't work,

Looked into documentation but didn't find anything with it.

**Comment by ainar-g** [comment]
<p>The&#xA0;config is just a&#xA0;<i>VimScript</i> hash, so&#xA0;you can
always&#xA0;do:</p> 

```vim
let clangd_server = {
\   'command': 'clangd',
\   'log_level': -1
\   'suppress_stderr': v:true,
\}
let g:lsc_server_commands = {
\   'c': clangd_server,
\   'cpp': clangd_server,
\}
```

**Comment by motorto** [comment]
Thanks! 
That makes it more organized and I like this solution so I will
close this issue
