### ISSUE TITLE
[Questions] Texlab errors on exit , and other questions 

### ISSUE THREAD

**Issue by motorto** [natebosch/vim-lsc#332]
Does someone here use [texlab](https://github.com/latex-lsp/texlab) , and could show me their configuration ? 

I am getting error messages at quitting the file.

https://imgur.com/a/mzanLLI

Is this an upstream problem or my config is wrong ? 
My vimrc looks like this:

```
let latex_server = {
			\	'command' : 'texlab',
			\	'workspace_config': {
			\		"latex.build.onSave":	"true",
			\		"latex.forwardSearch.executable": "zathura",
			\		"latex.forwardSearch.args": ["--synctex-forward", "%l:1:%f", "%p"]
			\	}
\}

let g:lsc_server_commands = {
			\'c': clangd_server,
			\'cpp': clangd_server,
			\'tex': latex_server,
\}
```
---- 

I am sorry to create a issue , when in reality is  a question about how to setup another language server. 

Couldn't find  a forum or irc :)

So instead of creating other issues here is some questions that I have: 
- Settings that I would put on settings.json (on coc.nvim) on vim-lsc I should put them on workspace_config right ? 
- I created a debug script like the wiki has , but on the server costumization where should I put it ? I tried to put it on command:'/home/user/debug.sh' , but that didn't work.

**Comment by Ambroisie** [comment]
I have the same issue, but only when editing a `*.tikz` file (after adding an `ftdetect/tikz.vim` file to `setfiletype tex` for those).

**Comment by motorto** [comment]
Glad to not be the only one :) If I may ask what distribution are you using ? (Just to know if you build from source , or are using the already made binaries)

**Comment by motorto** [comment]
Hum I tried the building from source and using the prebuilt binaries but got that errors all the time ... I have since gave up , but could you share your config for it . on vimrc ?

**Comment by Ambroisie** [comment]
Here are my [dot-files](https://gitea.belanyi.fr/Ambroisie/dot-files), with my config for `git-lsc` [here](https://gitea.belanyi.fr/Ambroisie/dot-files/src/commit/a13546856aae39bf4c7e8754f2bf74bfd756aba0/vim/.vim/plugin/settings/vim-lsc.vim)

**Comment by motorto** [comment]
Thanks, will open an issue on texlab git. I don't think that it's a vim-lsc one!
