### ISSUE TITLE
[Signature Help] Enable syntax highlighting?

### ISSUE THREAD

**Issue by bluz71** [natebosch/vim-lsc#345]
Hello Nate,

I have just started using `LSClientSignatureHelp`, I now find it useful when in insert mode, so I have defined this mapping:

```viml
inoremap <silent> <C-h> <C-o>:LSClientSignatureHelp<CR>
```

The main distraction is the lack of colors, especially when compared with hover whether floating or preview. Hover looks nice, signature help looks plain.

Signature help preview is defined in `autoload/lsc/signaturehelp.vim`, near the bottom of the file:

```viml
  if !has_key(signature, 'parameters')
    call lsc#util#displayAsPreview([signature.label], 'text',
        \ function('<SID>HighlightCurrentParameter'))
    return
  endif

  if has_key(a:signatureHelp, 'activeParameter')
    let active_parameter = a:signatureHelp.activeParameter
    if active_parameter < len(signature.parameters)
        \ && has_key(signature.parameters[active_parameter], 'label')
      let s:current_parameter = signature.parameters[active_parameter].label
    endif
  endif

  call lsc#util#displayAsPreview([signature.label], 'text',
      \ function('<SID>HighlightCurrentParameter'))
```

Notice the calls to `displayAsPreview` are setting `text` style.

If I replace those two instances with `&filetype`, that being the filetype of the current buffer I am wanting signature help on, then the preview window signature help will be syntax highlighted which makes it far easier to read.

Thoughts?

I will make a simple PR.

Best regards.

**Comment by natebosch** [comment]
I don't use signature help myself, but this looks like the right thing to do.

Closed with #346
