### ISSUE TITLE
Can't GoToDefinition using jdt.ls

### ISSUE THREAD

**Issue by anderson-silva-alianza** [natebosch/vim-lsc#361]
Hey guys,

I'm trying to work with jdt.ls but the only function that is working is FindReferences.

Below are my debugging of in and out of the execution.

[jdt_ls_in.log](https://github.com/natebosch/vim-lsc/files/5736446/jdt_ls_in.log)

[jdt_ls_out.log](https://github.com/natebosch/vim-lsc/files/5736447/jdt_ls_out.log)

And my configuration.

[lsc.txt](https://github.com/natebosch/vim-lsc/files/5736450/lsc.txt)

**Comment by anderson-silva-alianza** [comment]
I actually fix the problem! My configuration was incomplete.

I kinda copied from LanguageClient-neovim java setup https://github.com/autozimu/LanguageClient-neovim/wiki/Java

I just changed the configuration to consider the project directory.

```vim
'java': 'jdt_language_server -data ' . getcwd()
```

And the jdt.ls script ended up like this:

```sh
#/usr/bin/env sh

JDTLS=<path-to-jdt.ls>

java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
     -Dosgi.bundles.defaultStartLevel=4 \
     -Declipse.product=org.eclipse.jdt.ls.core.product \
     -Dlog.protocol=true \
     -Dlog.level=ALL \
     -noverify \
     -Xmx1G \
     -jar $JDTLS/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_<version>.jar \
     -configuration $JDTLS/org.eclipse.jdt.ls.product/target/repository/config_linux \
     --add-modules=ALL-SYSTEM \
     --add-opens java.base/java.util=ALL-UNNAMED \
     --add-opens java.base/java.lang=ALL-UNNAMED \
     "$@"
```

**Comment by natebosch** [comment]
Thanks for the info, sorry I wasn't able to take a look earlier.

Consider adding a section on configuring this server to the wiki to help others who might get stuck in the same way 😄 

https://github.com/natebosch/vim-lsc/wiki/Language-Servers
