### ISSUE TITLE
bufnr() needs arguments

### ISSUE THREAD

**Issue by justin2004** [natebosch/vim-lsc#387]
https://github.com/natebosch/vim-lsc/blob/c8d00fc7299d0ff73a37dcd7f6bb5564fb30d1a3/autoload/lsc/file.vim#L37

i am getting these errors when i open .js files:
```
Error detected while processing function <SNR>38_OnOpen[6]..lsc#file#onOpen:
line    5:
E119: Not enough arguments for function: bufnr
```

i can't even execute bufnr() without arguments:
```
:echom bufnr()
E119: Not enough arguments for function: bufnr
```

**Comment by lithammer** [comment]
I suspect maybe your version of Vim is too old? Works fine for me on both Vim 8.2.2400 and Neovim 0.5 nightly.

**Comment by natebosch** [comment]
It looks like I recently inadvertently introduced this incompatibility with older vims. I haven't made any concrete decisions about how long to promise compatibility, but I generally have been fixing things as they come up. Unfortunately I've been having a hard time also finding a way to reliably test against older versions on CI.

I'll open up a patch that adds the argument which is required in older vim versions.

**Comment by justin2004** [comment]
```
justin@parens:~$ vim --version                                      
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 19 2020 13:12:18)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401                                                                     
Modified by team+vim@tracker.debian.org                                                                                                 
Compiled by team+vim@tracker.debian.org
```

@lithammer when i installed this linux distro i forgot to pick a LTS.  :/ 
i'll have to upgrade soon.

**Comment by natebosch** [comment]
Should be fixed now.
