### ISSUE TITLE
Error starting neovim with metals

### ISSUE THREAD

**Issue by reidrac** [natebosch/vim-lsc#390]
When starting nvim with [metals](https://scalameta.org/metals/) 0.9.10 I get the following error:
```
[lsc:Error] Error dispatching message: 'Vim(for):E745: Using a List as a Number'
``` 
It doesn't seem to have any noticeable consequence and I can't see any errors in metals.log

I'm using current vim-lsc code from master with nvim v0.4.4.

Thanks for vim-lsc!

**Comment by natebosch** [comment]
I think this should be fixed in 53530bf2b53b8af7299aa6499ca30e74c90480ec

Can you try updating to the latest and see if this still happens?

**Comment by reidrac** [comment]
I thought I was already on latest!

Yes, it seems to be fixed now. Thanks!

**Comment by reidrac** [comment]
Sorry, I was wrong: it is still there.

I reproduced it running latest, on 53530bf2b53b8af7299aa6499ca30e74c90480ec

**Comment by reidrac** [comment]
Actually, it does have an effect in metals: when I change my builkd.sbt, the dialog asking me if I want to import the changes or not is not showing (I get the error instead).

**Comment by natebosch** [comment]
I shouldn't have jumped to conclusions - this is a different instance of the same bug. Sorry about that!
