### ISSUE TITLE
No diagnostics with solargraph/rubocop

### ISSUE THREAD

**Issue by axelbdt** [natebosch/vim-lsc#398]
Good morning,

Linting and diagnostics don't seem to work with solargraph/rubocop. Here is the lsc-related configuration :
```
" Language Server Configuration
let g:lsc_auto_map            = v:true
let g:lsc_enable_diagnostics  = v:true
let g:lsc_server_commands = {'ruby': 'solargraph stdio'}
```

And while running rubocop on a malformed file does produce error :
```
hello.rb:10:1: E: Lint/Syntax: unexpected token $end
(Using Ruby 3.0 parser; configure using TargetRubyVersion parameter, under AllCops)
```

While autocompletion does seem to work, nothing is displayed in the editor while editing or running ```:LSClientAllDiagnostics```

Is support missing or am I the one missing something ?

Cheers,

```
ruby 3.0.0p0
solargraph 0.40.3
rubocop 1.9.1
vim 8.1
```

**Comment by lithammer** [comment]
Seems like diagnostics is disabled by default (see https://github.com/castwide/solargraph/blob/045c60c4e5911c91d8b33e8ee0eee6b74fa8fe98/lib/solargraph/language_server/host.rb#L619) in Solargraph.

**Comment by natebosch** [comment]
Looks like you should be able to enable diagnostics in the `intialize` call.

```viml
  let g:lsc_server_commands = {'ruby': {
      \ 'name': 'solargraph',
      \ 'command': 'solargraph stdio',
      \ 'message_hooks': {
      \   'initialize': {
      \     'initializationOptions': {
      \       'diagnostics': v:true
      \     }
      \   },
      \ },
      \}}
```
