### ISSUE TITLE
Highlight first item in autocompletion

### ISSUE THREAD

**Issue by aonemd** [natebosch/vim-lsc#399]
I'm trying to enable highlighting the first item in the suggestion list of autocomplete.
Is this LSC related or Vim related?

**Comment by aonemd** [comment]
Found it. I had to set the option `g:lsc_auto_completeopt` to:

```vimscript
 let g:lsc_auto_completeopt='menu,menuone,noinsert,noselect'
```

Is it weird that LSC didn't use Vim's `completeopt` right away or am I missing something?

**Comment by natebosch** [comment]
> Found it. I had to set the option `g:lsc_auto_completeopt` to:
> 
> ```
>  let g:lsc_auto_completeopt='menu,menuone,noinsert,noselect'
> ```

Hmm, do you mean

```viml
 let g:lsc_auto_completeopt='menu,menuone,noinsert'
 ```
 
 What you have looks like it should behave the same as the plugin does by default.
 
 The reason that the plugin needs to modify the `completeopt` setting is that some values like `longest`, or not using `noInsert` can interfere with behavior.
 
 I'm not actually sure why I put `noselect` in the defaults though, taking a closer look now it can't see any reason why it would negatively impact behavior - I suspect it was just the setting I happened to use at the time.
 
 Playing with it now I think that omitting `noselect` is a better default, so I'll go ahead and switch to that.

**Comment by aonemd** [comment]
Yes, exactly, I meant:

```vim
 let g:lsc_auto_completeopt='menu,menuone,noinsert'
```

Thank you for quickly responding and handling the issue.
