### ISSUE TITLE
Noticeable delay when exiting Vim

### ISSUE THREAD

**Issue by aonemd** [natebosch/vim-lsc#406]
I updated `vim-lsc` recently and now whenever I try to exit Vim no matter the language or the language server I'm using I get some delay with the following messages:
> Waiting for language server exit: 'clangd --background-index'

> Waiting for language server exit: 'solargraph stdio'

> Waiting for language server exit: 'typescript-language-server --stdio'

> Waiting for language server exit: 'rls'

**Comment by natebosch** [comment]
This is the client waiting for the response to the `shutdown` request, before it sends an `exit` request.

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#shutdown

I'm not entirely sure how important these are to most language servers, but to follow the spec the client should send them both.

One thing that isn't entirely clear to me, I wonder if it would be OK to send the `exit` immediately after the `shtudown`. There is a discussion that I think implies it isn't OK, but I filed an issue to hopefully get some clarity. https://github.com/microsoft/language-server-protocol/issues/1226

This client does have a timeout before it gives up waiting for the `shutdown` response, and I could certainly make that timeout configurable. I'm mostly hesitant to do that because I don't know what the consequences are for most servers.

**Comment by aonemd** [comment]
Yeah, I saw the 5 second timeout limit. Maybe this can be configurable.
It's a weird situation (at least to me) having the client make sure that the server terminates correctly.

Thanks for taking the time to reply.

**Comment by ldrumm** [comment]
I spent a little time debugging this and have found the following:

1. vim-lsc is correctly sending the shutdown request (sent in `s:Kill`)
2. clangd correctly sends the null response to that request. It is processed in
3. vim receives the message 
4. the callback defined in s:Kill is never triggered and so the shutdown notification is never sent by vim
I added some logging:
```diff
diff --git a/autoload/lsc/protocol.vim b/autoload/lsc/protocol.vim
index c3c4b5c..98e60d5 100644
--- a/autoload/lsc/protocol.vim
+++ b/autoload/lsc/protocol.vim
@@ -117,6 +117,7 @@ function! s:ContentLength(headers) abort
 endfunction
 
 function! s:Dispatch(message, OnMessage, callbacks, ...) abort
+ call ch_log('got dispatch message: ' . json_encode(a:message))
   try
     if has_key(a:message, 'method')
       let l:method = a:message.method
diff --git a/autoload/lsc/server.vim b/autoload/lsc/server.vim
index 19caeae..a08dab3 100644
--- a/autoload/lsc/server.vim
+++ b/autoload/lsc/server.vim
@@ -78,6 +78,7 @@ endfunction
 " was made because the server is not currently running.
 function! s:Kill(server, status, OnExit) abort
   function! Exit(result) closure abort
+    call ch_log('Exit called')
     let a:server.status = a:status
     if has_key(a:server, '_channel')
       " An early exit still could have remove the channel.
@@ -86,6 +87,7 @@ function! s:Kill(server, status, OnExit) abort
     endif
     if a:OnExit != v:null | call a:OnExit() | endif
   endfunction
+  call ch_log('sending shutdown request')
   return a:server.request('shutdown', v:null, funcref('Exit'))
 endfunction
 
```
but "Exit called" is never printed and "got dispatch message" isn't printed for the shutdown response
The `ch_logfile` [log](https://github.com/natebosch/vim-lsc/files/6167987/lsc.log) is attached.

Additionally I ran a bisection and found that 806d3c01ca4391fbc054e2370de1d126b49d1f77 is the commit that introduces the error.

I'm guessing this is simply a dispatch error. The protocol logic seems to be in spec and clangd is adhering to it too

Let me know if I can help debug this more

**Comment by natebosch** [comment]
@ldrumm - Thanks for the investigation. The commit you found with the bisect made this clear - I should be able to fix it.

**Comment by ldrumm** [comment]
> Closed #406 via #407.
This is working for me. Thanks for the quick fix.

**Comment by inside** [comment]
Hi guys, I installed the latest version of vim-lsc and the delay still happens on my side with this message: `Waiting for language server exit: 'typescript-language-server --stdio'`. Can you tell me if I missed something? Thanks

**Comment by cnbuff410** [comment]
I ran into this issue as well, fresh installation, new computer, everything is just installed. Everything works as expected except the exiting delay. MBP 16 with macOS Monterey.

I really want to make it work before switching to another LSP server. Any suggestions would be appreciated.

**Comment by cnbuff410** [comment]
@inside Did you end up resolving this issue?

**Comment by inside** [comment]
> @inside Did you end up resolving this issue?

Unfortunately not, but glad to know I'm not forever alone :-)

**Comment by cnbuff410** [comment]
Did you switch to another library, or did you learn to tolerate the delay? 

I'm willing to do some debugging if someone can provide instructions. I don't know vimscript so not sure where should I start.

**Comment by inside** [comment]
> Did you switch to another library, or did you learn to tolerate the delay?

I learned to not quit vim as often as I did

> I'm willing to do some debugging if someone can provide instructions. I don't know vimscript so not sure where should I start.

I believe earlier comments in this issue will give some hints about where the solution is.
If you want to learn more about vimscript I'd suggest this site: https://learnvimscriptthehardway.stevelosh.com/

**Comment by cnbuff410** [comment]
I am happy to generate logs and do things like that, but I don't think I have time to learn vimscript from scratch:)

**Comment by ldrumm** [comment]
On Fri Nov 5, 2021 at 5:02 PM GMT, Kun wrote:
> I am happy to generate logs and do things like that, but I don't think I
> have time to learn vimscript from scratch:)

I know a bit of vimscript and I'm happy to try and reproduce as I've had a poke
around in this area before. To help, I'll need you to provide the output from
the following:

    vim --version
    typescript-language-server --version

Please also run

    vim --cmd "call ch_logfile('logfile', 'w')"`

and upload `logfile` after a session that hangs and you've quite. Note that it
will include all data sent and received on vim's channels so don't do anything
confidential.

Please also provide all non-default `g:lsc_` settings from your .vimrc and the
exact vim-lsc plugin git version (git rev-parse HEAD)

**Comment by cnbuff410** [comment]
For sure!

**vim --version**                                                                                                                                                                                            
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 21 2021 10:39:53)
macOS version - arm64
Included patches: 1-3550
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      -sodium            -xfontset
+digraphs          +mouse             -sound             -xim
-dnd               -mouseshape        +spell             -xpm
-ebcdic            +mouse_dec         +startuptime       -xsmp
+emacs_tags        -mouse_gpm         +statusline        -xterm_clipboard
+eval              -mouse_jsbterm     -sun_workshop      -xterm_save
+ex_extra          +mouse_netterm     +syntax            
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/opt/homebrew/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: clang -L. -fstack-protector-strong -L/opt/homebrew/lib -L/opt/homebrew/opt/libyaml/lib -L/opt/homebrew/opt/openssl@1.1/lib -L/opt/homebrew/opt/readline/lib -o vim -lm -lncurses -liconv -lintl -framework AppKit -L/opt/homebrew/opt/lua/lib -llua5.4 -mmacosx-version-min=12.0 -fstack-protector-strong -L/opt/homebrew/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE -lperl -L/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -lpython3.9 -framework CoreFoundation -lruby.3.0 -L/opt/homebrew/Cellar/ruby/3.0.2_1/lib
```

I used Go language server `gopls`, the version is `v0.7.3`.

I attached the logfile. I just opened a Go file and closed it. Nothing else
[logfile.zip](https://github.com/natebosch/vim-lsc/files/7489323/logfile.zip)
.

For vimrc settings this is all I have for vim-lsc:

```
let g:lsc_server_commands = {
\  "go": {
\    "command": "gopls serve",
\    "log_level": -1,
\    "suppress_stderr": v:true,
\  },
\}

let g:lsc_auto_map = v:true
let g:lsc_enable_diagnostics = v:true
```

The HEAD of the vim-lsc plugin git version is 

`4b0fc48037c628f14209f30616a19287d9e54823`

Please let me know if you need anything else!

**Comment by ldrumm** [comment]
On Fri Nov 5, 2021 at 11:41 PM GMT, Kun wrote:
> I used Go language server `gopls`, the version is `v0.7.3`.
Good to know. Thanks

> I attached the logfile. I just opened a Go file and closed it. Nothing else
> [logfile.zip](https://github.com/natebosch/vim-lsc/files/7489323/logfile.zip)

This log is very interesting! When vim-lsc sends the shutdown request, gopls
sends a window notification before responding to the request with the null
response as per the spec.
```
{"method":"shutdown","jsonrpc":"2.0","id":3}'
  3.249828 : ui_delay(20)
  3.270123 RECV on 0(out): 'Content-Length: 139^M
^M
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2021/11/05 17:38:12 Shutdown session\n\tshutdown_session=1\n"}}Content-Length: 38^M
^M
{"jsonrpc":"2.0","result":null,"id":3}'
```

I modified my own in-development language server to emulate this behaviour, and
can reproduce the hang 100%.

I'm not sure whether gopls is [in
spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#shutdown),
but from a cursory re-reading it doesn't look like servers are forbidden from
sending notifications after a shutdown request. Indeed, it's perfectly possible
for a server to send any notification at any time, and the user might happen to
exit their editor as that even is received, meaning a race condition baked into
the protocol.

We should try and handle this in vim-lsc. I'll take a whack at it and post back
later.

**Comment by cnbuff410** [comment]
Awesome, let me know if I can provide any other shallow level help:)

**Comment by cnbuff410** [comment]
Is there any update on this issue?

**Comment by Integralist** [comment]
👋🏻 I'm also seeing this issue while using gopls. 

I just switched from another LSP client to this one and was very happy until I `:q` and realised the delay in exit 😄 

I'm using the latest version of vim-lsc and my vim version is:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 11 2020 13:03:49)
macOS version
Included patches: 1-1830
Compiled by integralist@Marks-MacBook-Pro.local
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/local/lib  -L/usr/local/lib -o vim        -lm -lncurses  -liconv -lintl -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/Users/integralist/.pyenv/versions/3.9.0/lib/python3.9/config-3.9-darwin -lpython3.9 -lintl -framework CoreFoundation  -lruby.2.6     
```
