### ISSUE TITLE
E121: Undefined variable: g:lsc_enable_diagnosticsa

### ISSUE THREAD

**Issue by julien** [natebosch/vim-lsc#419]
First of all thanks for this plugin, great stuff.

I recently updated to the latest release and when editing files, I'm not getting this error

```
Error detected  while processing function <lambda>3[1]..6[18]...lsc#diagnostics#clean[3]...lsc#diagnostics#setForFile:
line 1:
E121: Undefined variable: g:lsc_enable_diagnosticsa
```

I don't know much about vimscript; but searching in the codebase I found [this line](https://github.com/natebosch/vim-lsc/blob/2f0cbbfb8ea8997b408e447a2bc9554a3de33617/autoload/lsc/diagnostics.vim#L65) and was wondering if that was the problem. If it is, I can send a pull request.

**Comment by aonemd** [comment]
Hello @julien this is an issue that's fixed in this PR https://github.com/natebosch/vim-lsc/pull/415 but we're still waiting for a merge.

**Comment by julien** [comment]
@aonemd thanks for the heads up, I didn't find in the issues so that's why I created one.
Since it's been taking care feel free to close.

**Comment by julien** [comment]
@aonemd this issue is actually a duplicate of #418, so closing here. Thanks
