### ISSUE TITLE
Show a message if a server call fails

### ISSUE THREAD

**Issue by jacwah** [natebosch/vim-lsc#42]
This is related to #41, but in addition to giving feedback when a server crashes, it would be helpful to see if a command failed to execute.

`lsc#server#call` already returns boolean indicating if a call was successful or not. Yet, none of the call sites propagate this information to the user.

**Comment by natebosch** [comment]
Do you mean in the case where the server isn't running?
https://github.com/natebosch/vim-lsc/blob/master/autoload/lsc/server.vim#L76

I think we might be relying on this being silent in some cases, but I'm not sure if that is still true. I will do some experimentation and see.

**Comment by jacwah** [comment]
Yes. There are also a few more points in the linked function where an error is detected and `v:false` returned.

I mentioned the reason for bringing this up in #41. I tried using a failing server and each command would fail silently.
