### ISSUE TITLE
Option to close selection window after selection

### ISSUE THREAD

**Issue by smekkley** [natebosch/vim-lsc#422]
After finding some references  and selecting it, the window seems to stay opened.
Is there a configuration option to close it automatically like ctags, cscope?

**Comment by aonemd** [comment]
This is the expected behavior from Quickfix lists. I prefer to keep the closing behavior up to the user rather than enforcing it by default.

**Comment by smekkley** [comment]
Having `autocmd BufLeave * cclose` in vimrc is the right solution for this.
