### ISSUE TITLE
A way to keep hover info shown

### ISSUE THREAD

**Issue by smekkley** [natebosch/vim-lsc#426]
When vim-lsc finds function suggestion, a nice hover appears about the function, but as soon as I start typing function argument, it disappears, is there way to keep it shown? Or is it language server limitation? I use clangd for C and C++ projects.  
I'd appreciate if it keep showing even if it is wrong for overloaded functions. But right now, it doesn't work with normal functions either.

**Comment by arp242** [comment]
Did you try pressing `K`? If I press it once on an identifier I get the "hover", and if I press it twice I get the preview window.

I think this is the default behaviour – I don't recall doing anything special for this anyway.

**Comment by smekkley** [comment]
I think I was mistaken with completion which also suggests function arguments, wasn't a hover, which works for already complete functions.  
  
My dilemma is that as soon as I type `(` for example after writing a function, neither K nor suggestion works. I have to delete `(` to make the suggestion or K works.  

If `K` works even in a situation like `printf(` instead of `printf` or `printf("1")`, and won't disappear immediately after I type, it'll be really great.  
Do you think vim or vim-lsc allow such implementation?

**Comment by smekkley** [comment]
After looking through the code, I think this is tricky to achieve. 
It's pretty language server dependent, vim-lsc's job is to just send the current line and column location.
Some language server responds with the textDocument even when the function signature doesn't seem to match, but that's not the case with clangd.   
In case of python,(`jedi-language-server`), `K` seems to work based on cursor location, no matter how incomplete or wrong the function argument is, so it doesn't work if your cursor is inside the function argument.

https://github.com/prabirshrestha/vim-lsp/issues/275 describes what I want in gif, but I don't think no vim language server protocol clients support it, as it requires some sort of best effort attempts.

**Comment by natebosch** [comment]
Does `set completopt+=preview` help at all?

It's not a hover window, but you might at least be able to have the information you are hoping for on screen, and you can close it without leaving your buffer with `<c-w><c-z>`

I'm not sure if I'll be able to find a nice UX for keeping a consistent floating window up while typing the arguments.

**Comment by smekkley** [comment]
It doesn't. 
I'm also using https://github.com/yegappan/lsp but it seems to support it. The suggestion appears on top of cursor as soon as it enters function arguments.

**Comment by smekkley** [comment]
I guess it's usable by like this.  

1. Type in function without bracket.
2. Escape
3. Press KK to show lsc_preview on top
4. Start typing. As long as argument does not match something, lsc_preview window will be kept.

Maybe it'll be nice to show what K shows automatically in lsc_preview window by default and not update it automatically during function argument.

**Comment by smekkley** [comment]
It seems what I wanted was signaturehelp which is supported by vim-lsc. I just made it to use popup_at_cursor and the problem solved.
