### ISSUE TITLE
Make vim-lsc work with ltex-ls

### ISSUE THREAD

**Issue by Lodifice** [natebosch/vim-lsc#437]
Hello, I just discored the language server ecosystem and wanted to set up vim-lsc with [ltex-ls](https://github.com/valentjn/ltex-ls).
The classic `let g:lsc_server_commands = {'tex': 'ltex-ls'}` does, however, not work:

```
[lsc:Error] StdErr from ltex-ls: FEIN: Skipping text check as LTeX has been disabled for files with code language ID 'tex' via ltex.enabled
```

It appears that language servers can restrict themselves to certain language IDs, which would include "latex", but not "tex", for ltex-ls.
However, vim-lsc seems to report "tex" (I guess since the Vim filetype is called that way).
Is there any posibility to change this?
I did not find one.
Ideally would be to add a possibility to map the Vim filetype to a language ID.

Then I added a modeline which forces my latex file into filetype "latex" (I just made up that one) and set `let g:lsc_server_commands = {'latex': 'ltex-ls'}`.
Now the error from above is gone, but `:LSClientAllDiagnostics` gives me an empty quickfix list.
The language server seems to do its part according to the stderr output:

```
[lsc:Error] StdErr from ltex-ls: FEIN: Checking the following text in language 'en-US' via LanguageTool: "\n\n\n\n\n\nThis is an document. Its contains an errors.\n\n"
[lsc:Error] StdErr from ltex-ls: FEIN: Obtained 2 rule matches
```

Maybe some with experience in exotic language servers can help here.

**Comment by natebosch** [comment]
See `:help lsc-setup`, (and `:help lsc-server-languageId` describes the specif config)

In particular you'd expand to the longer form for defining a server and add a `languageId` value.

```viml
 let g:lsc_server_commands = {                                   
     \ 'tex': {                                                                                                                     
     \   'command': 'ltex-ls',                                                  
     \   'languageId': 'latex',                                        
     \ },                                                                      
     \}
```

**Comment by Lodifice** [comment]
Thanks, this definitely helps in setting up language servers.

However, I know get the same problem like when I hack the file type, i.e. an empty quickfix list. So I guess `vim-lsc` isn't compatible with `ltex-ls`, or was someone able to get it to work? Since the issue name is misleading now, I'll create a new one if you like.

**Comment by natebosch** [comment]
We can use this issue to keep digging on the second problem. I'll see if I can install this server and repro.

**Comment by Lodifice** [comment]
Thanks for having a look! I was able to install it under coc: https://valentjn.github.io/ltex/vscode-ltex/installation-usage-coc-ltex.html

So maybe ltex-ls uses a non-standard way of communicating hints?

**Comment by natebosch** [comment]
I did notice that this server needs one extra bit of config to be usable.

```viml
 let g:lsc_server_commands = {
     \ 'tex': {
     \   'command': 'ltex-ls',
     \   'languageId': 'latex',
     \   'suppress_stderr': v:true,
     \ },
     \}
```

Diagnostics worked for me the first time I tried. If you had set `g:lsc_enable_diagnostics` to `v:false` then they'd be ignored when the server sends them, but otherwise I'm not sure why they wouldn't show up in `:LSClientAllDiagnostics`.

**Comment by Lodifice** [comment]
Thank you for the `suppress_stderr` hint, it makes life easier.

Regarding the diagnostics window, I indeed accidentally set `g:lsc_enable_diagnostics` to false when I experimented with the file type and forgot to turn it back on. Thanks for pointing me into the right direction and sorry for bothering you!
