### ISSUE TITLE
support filtering trigger characters

### ISSUE THREAD

**Issue by sigmundch** [natebosch/vim-lsc#444]
Consider providing an option to filter/block some trigger characters that are listed by the LSP server. This will allow clients to customize whether or not they would like completion on certain contexts.

For me, the use case is to disable completion only on `{` when editing Dart code.

**Comment by natebosch** [comment]
I'm leaning towards this being a global option. We could add a server specific way to configure this if someone requests it, but I'd guess that most of them time an author is going to have consistent preference across languages.
