### ISSUE TITLE
No highlighting using a non-default colour scheme

### ISSUE THREAD

**Issue by vp-elitnet** [natebosch/vim-lsc#461]
First noticed using ["solarized"](https://github.com/altercation/vim-colors-solarized), reproduced with ["solarized8"](https://github.com/lifepillar/vim-solarized8) and even the bundled colour schemes, e.g. "morning".

Errors are displayed using "lopen", but not highlighted. Error highlighting works after executing `highlight link lscDiagnosticError Error`, but does not work if the command is put into vimrc.

The issue is reproducible with the following minimal vimrc.

	syntax enable
	colorscheme morning

	let g:lsc_server_commands = {
				\ 'erlang': 'erlang_ls -t stdio'}

Reproducible using both v0.4.0 and master (39ec72353c2170db2caf797072800c513647e9c5) using Vim 8.2.2434-3+deb11u1 on Debian stable.

**Comment by natebosch** [comment]
Is it possible you have some other config which sets that highlight group?

The plugin will create that group as a link, but only if it doesn't exist. If it doesn't work to put that command into `vimrc` it also suggests something could be overwriting it.

Can you try running `:verbose highlight lscDiagnosticError` and see if it is being configured anywhere unexpected?

**Comment by vp-elitnet** [comment]
I neglected to mention I was testing using gvim. Your reply prompted me to look at the file sourcing order in the verbose output and that reminded me of ~/.gvimrc. My .gvimrc is short and simple, but the offending line seems to be `set background=light`. I suppose setting `background` after vim-lsc is loaded is the issue - the same line in ~/.vimrc does not trigger the issue.

Sorry for the noise!
