### ISSUE TITLE
Add ability to customize params per request

### ISSUE THREAD

**Issue by natebosch** [natebosch/vim-lsc#51]
Some language servers can take advantage of additional metadata on certain calls. Add a hook so that users can customize/override parameters sent on each request.

See discussion at https://github.com/natebosch/vim-lsc/pull/50

**Comment by natebosch** [comment]
Might be good to implement this on top of https://github.com/natebosch/vim-lsc/issues/39 rather than add another global variable.

**Comment by natebosch** [comment]
@hia3 - please let me know if this approach works for you.

See `:help lsc-server-message_hooks` for documentation and an example of how to set this up.

**Comment by hia3** [comment]
@natebosch It works like a charm, thank you!

**Comment by natebosch** [comment]
As an FYI after #64 this can have a bit nicer syntax:

```viml
 let g:lsc_server_commands = {
     \ 'c': {
     \    'command': 'clangd',
     \    'message_hooks': {
     \        'textDocument/didOpen': {'metadata': {'extraFlags': ['-Wall']}},
     \    },
     \  },
     \}
```
