### ISSUE TITLE
document which Vim versions are supported (only Vim >= 8? neovim too?) somewhere

### ISSUE THREAD

**Issue by guillaume-d** [natebosch/vim-lsc#52]
I could not find this information anywhere in the docs or in GitHub bugs/PRs.

Also maybe some Vim plugins are required (or just recommended)?

**Comment by cmpadden** [comment]
I am also interested to know which versions are supported.

It appears that the job API differs between Vim and Neovim. For example, `job_start`, which is used in [server.vim](https://github.com/natebosch/vim-lsc/blob/4e537fa0d2e126bfe0a089f631e129e656544a76/autoload/lsc/server.vim#L112) is not supported in Neovim.

```
E117: Unknown function: job_start
E15: Invalid expression: job_start(command, job_options)
```

**Comment by natebosch** [comment]
Good idea!

I'll update the readme soon. This is `vim` only, `neovim` indeed has different async job apis and this plugin does not use them. Version 8 should be compatible, also some high patch levels from version 7 I'd imagine.

`job_start` is the most likely thing that I'm using from recent versions, but there might also be a few other bits that are new since backwards compatibility hasn't been a goal. I'll try to make this clear in the README.

**Comment by prabirshrestha** [comment]
[async.vim](https://github.com/prabirshrestha/async.vim) can be used to normalize jobs between vim8 and neovim.

**Comment by natebosch** [comment]
@prabirshrestha - yeah I did check out that plugin and I think you did a great job with it. I'm a bit torn on using it. On the one had I like the idea of being cross compatible. On the other hand I _really_ dislike asking users to install dependencies to use a plugin. I wish the vim plugin ecosystem had a solution here.

I'm also nervous about claiming to support both neovim and vim when I don't use them both myself. Long term I should probably invest some time in automated testing, but for the time being I'm mostly relying on the fact that I use the plugin day to day to notice regressions.

**Comment by prabirshrestha** [comment]
@natebosch you can ship async.vim with your plugin so you don't need to tell others to install it separately. Just make sure to rename the public api's at the end. There is a doc in README.md about embedding.

Here is an example: https://github.com/k-takata/minpac

**Comment by natebosch** [comment]
@prabirshrestha - I checked it out but it looks like I can't quite switch to it since there is no support for replacing `ch_open`. I see you're looking at how to get that done in neovim (https://github.com/neovim/neovim/issues/4479) but AFAICT there is no relevant replacement - is that correct?

**Comment by natebosch** [comment]
As an FYI I've added support for neovim. Tested with neovim 0.2.0

I ended up writing my own abstraction over `job_start` and `jobstart` so I could hide some of the details that went towards features I'm not using.
