### ISSUE TITLE
Docker Language Server

### ISSUE THREAD

**Issue by adelarsq** [natebosch/vim-lsc#60]
I'm trying to use the [docker language server](https://github.com/rcjsuen/dockerfile-language-server-nodejs) but with no success. This is my config:

```
let g:lsc_server_commands = {
'dockerfile': 'docker-langserver --stdio'
}
```

The plugin appears to initiate, but the callback function never execute.

In the docker language server docs shows that: ``"When writing directly to the process's stdin, the additional Content-Length header must be included. Similarly, when reading from the process's stdout, the header will be included in the response message."``

This plugin doesn't include the content-length header in the message or are there something wrong in configs?

Enviroment:
- Windows 10
- Gvim 8 - Patch 1418

**Comment by natebosch** [comment]
We do include the `Content-Length` header. That's done here: https://github.com/natebosch/vim-lsc/blob/9fb4379dde23d59327aa325190a7b4049a3430e3/autoload/lsc/protocol.vim#L43

I wonder if this server is expecting a `workspace/didChangeConfiguration` message before it does something useful?
https://www.npmjs.com/package/dockerfile-language-server-nodejs#language-server-settings

It would be helpful if you could log the communication with the server and even more helpful if you are able to log some communication with a client that is known to work.

**Comment by adelarsq** [comment]
I was using on Windows. On OSX shows this message:
![image](https://user-images.githubusercontent.com/430272/34785857-893a273a-f619-11e7-9ee0-c1f8defa1830.png)

**Comment by natebosch** [comment]
That almost makes me think the process isn't listening on stdin.

We could set things up to allow the command to be `['docker-langserver', '--stdio']` but `:help job_start()` explicitly says that a String command works best on windows.

**Comment by prabirshrestha** [comment]
Some of the things I learned when writing [vim-lsp](https://github.com/prabirshrestha/vim-lsp).

If you are running script files don't use `['script', '--stdio']`. It works on mac and linux but not on windows. In windows you can't run .bat or .cmd file directly.
Use this instead. `[&shell, &shellcmdflag, 'docker-langserver --stdio']` so it works on all platforms. Also notice how `docker-langserver --stdio` is the third argument and not multiple.

Verified that docker lang server is working with vim-lsp. I have been writing some of these edge cases in the vim-lsp docs at https://github.com/prabirshrestha/vim-lsp/blob/master/doc/vim-lsp.txt

**Comment by natebosch** [comment]
@prabirshrestha - thanks for the tips!

I wonder if it makes sense to handle the `[&shell, &shellcmdflag,` part inside the plugin. I think I've already been expecting that the command is a String rather than a list so this should work with most existing config. It works with the config I use on linux.
Do you know of a place where this wouldn't work?

**Comment by adelarsq** [comment]
Apparently it's a [bug](https://github.com/rcjsuen/dockerfile-language-server-nodejs/issues/198).
@prabirshrestha I'm using vim-lsp documentation to configure vim-lsc servers.

**Comment by adelarsq** [comment]
It's working on OSX, was related with the bug.
I don't know about Windows. I will have a Windows machine only on 2 weeks.

**Comment by prabirshrestha** [comment]
@natebosch For me I prefer not to have any magic in my vim plugins. 

* Given that vim is very portable and used in many platforms I prefer to push these logic to the user so as a plugin author I don't need to fix all possible config issues.
 If you use `&shell` you might need to force using `cmd.exe` in windows in most of the cases. But if the user wants to run a cygwin script you don't want to use `cmd.exe`.
Also you don't need to worry about escaping arguments that have spaces.
Having a wiki or readme instructions that is copy pasteable works here.
* In windows communication with stdin/stdout is a bit slow so I avoid using it if there is an executable that can be run directly. (I personally haven't benchmarked this but would love to see this happening https://github.com/vim/vim/issues/2115)

You could also get the best of the world by checking if string use `&shell` if array don't use `&shell`.

**Comment by prabirshrestha** [comment]
Also windows doesn't support `fork()` so using `&shell` starts two process `cmd.exe` and the actual executable.

**Comment by adelarsq** [comment]
Closing issue since the related problem was solved.
