### ISSUE TITLE
The documentation should warn that you need the beta channel of Dart.

### ISSUE THREAD

**Issue by jtmcdole** [natebosch/vim-lsc#61]
I was unable to get lsc running on the stable 1.24.3 dart release (Ubuntu 16.04).  I would keep getting an error on autocomplete about 'not connected'.  Running the dart_language_server directly gave the following output:

```shell
 /usr/lib/dart/bin/dart /usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot --sdk /usr/lib/dart                                                        
{"event":"server.connected","params":{"version":"1.18.0","pid":20577,"sessionId":""}}
```

Updating to Dart 2.0 on the beta channel has errors and jump-to working.  Running the same command above yields:

```shell
{"event":"server.connected","params":{"version":"1.18.4","pid":27666,"sessionId":""}}
```

**Comment by natebosch** [comment]
Moved to https://github.com/natebosch/dart_language_server/issues/21

I don't think this issue is related to the vim side.
