### ISSUE TITLE
Help debugging Windows 10

### ISSUE THREAD

**Issue by jtmcdole** [natebosch/vim-lsc#66]
I'm attempting to get vim-lsc working in Windows.  So far:

* install dart 2.0.0-dev.15.0
* install dart_language_server as documented
* install vim 8.0 in both "git-bash" and windows native
* set `let g:lsc_server_commands = {'dart': 'dart_language_server.bat'}` in ~/.vimrc

I can open files, but completion returns a file error. Random hacking in the vim-lsc base for debugging turned up two things; in git-bash the uri is 'file:///c/Users/...' which doesn't work. Under the cmd.exe, the file path is a string of encoded characters.  Even if I corece this into a URI that makes sense (`file:///C:/User/...'), I still get the same error.

Is there a better way to go about  debugging this in vim or should I just try raw commands to the dart_language_server till I get a response that works? 

```shell
{"method":"textDocument/definition","jsonrpc":"2.0","id":2,"params":{"textDocument":{"uri":"file:///C%3a%5cUsers%5ccodefu%5cdart%5ctesla_dart%5clib%5cvehicle.dart"},"positio
n":{"character":3,"line":23}}}
callback!
payload:  {"jsonrpc":"2.0","error":{"code":-32000,"message":"[Analyzer RequestError method: analysis.getNavigation, code: GET_NAVIGATION_INVALID_FILE, message: Error during `ana
lysis.getNavigation`: invalid file.]","data":{"full":"[Analyzer RequestError method: analysis.getNavigation, code: GET_NAVIGATION_INVALID_FILE, message: Error during `analysis.g
etNavigation`: invalid file.]","stack":"package:dart_language_server/src/shim.dart 186          AnalysisServerAdapter.textDocumentDefinition.<fn>\n===== asynchronous gap =======
====================\ndart:async/future.dart 222                              new Future.sync\npackage:pool/pool.dart 126                              Pool.withResource.<fn>\nda
rt:async/zone.dart 1134                               _rootRunUnary\ndart:async/zone.dart 1031                               _CustomZone.runUnary\ndart:async/future_impl.dart 12
9                         _FutureListener.handleValue\ndart:async/future_impl.dart 633                         _Future._propagateToListeners.handleValueCallback\ndart:async/futu
re_impl.dart 662                         _Future._propagateToListeners\ndart:async/future_impl.dart 477                         _Future._completeWithValue\ndart:async/future_imp
l.dart 507                         _Future._asyncComplete.<fn>\ndart:async/zone.dart 1126                               _rootRun\ndart:async/zone.dart 1023
         _CustomZone.run\ndart:async/zone.dart 925                                _CustomZone.runGuarded\ndart:async/zone.dart 965                                _CustomZone.bin
dCallbackGuarded.<fn>\ndart:async/schedule_microtask.dart 41                   _microtaskLoop\ndart:async/schedule_microtask.dart 50                   _startMicrotaskLoop\ndart:
isolate-patch/dart:isolate/isolate_patch.dart 111  _runPendingImmediateCallback\ndart:isolate-patch/dart:isolate/isolate_patch.dart 164  _RawReceivePortImpl._handleMessage\n","r
equest":{"method":"textDocument/definition","jsonrpc":"2.0","id":2,"params":{"textDocument":{"uri":"file:///C%3a%5cUsers%5ccodefu%5cdart%5ctesla_dart%5clib%5cvehicle.dart"},
"position":{"character":3,"line":23}}}}},"id":2}
LSC Error!: [Analyzer RequestError method: analysis.getNavigation, code: GET_NAVIGATION_INVALID_FILE, message: Error during `analysis.getNavigation`: invalid file.]
```

**Comment by natebosch** [comment]
Another user saw an issue with windows file paths and fixed it with #48 

Perhaps there are some differences between running in git-bash vs windows vim?

I wonder if we should replace `\` with `/` in the path before doing the URI encode. I'm very unsure about the `c` vs `C:` distinction, but I should also maybe not URI encode that `:`?
I will try to get this running on a windows box and play around with it a bit. If I do need to switch slash types this could get a little messy since we need to be able to round trip paths through the server and get the same value back suitable for use as a dict key.

**Comment by jtmcdole** [comment]
I have a running windows box, so I can certainly help out. 

I'm testing both gitbash and windows vim.  Windows VIM has gobbledygook path since it was encoding `\` as `%5c`, so I hacked that to replace `\` with `/`. `C` vs `c` shouldn't matter as its case insensitive. I tested the final URI that I made with just a simple dart program and tests `existsSync()` which returned true, so I know the URI is 'clean'.  I may not have hit all the locations where the URI is looked at (I believe there is a preamble message that goes to dart_language_server to initialize the repo and sdk?).

When debugging, do you generally just fire up the `dart_language_server` on the command line and send json in the raw?

**Comment by natebosch** [comment]
> When debugging, do you generally just fire up the `dart_language_server` on the command line and send json in the raw?

It's really annoying to try that since you also need to count the length of the json for the message header.

I think what you can do is something like this inside vim (these APIs aren't necessarily stable but they should work for now):

```viml
let server = lsc#server#servers()['dart_language_server']
" Can see some debug info, like the last 10 sent and received messages
" in server.calls and server.messages respectively
call server.send({'method': 'textDocument/didOpen', 'param': {...}, 'id': 1000})
```


If you think it would be helpful I could add a mode to `dart_language_server` that would accept JSON input without the LSP headers to make it easier to manually send messages.

**Comment by jtmcdole** [comment]
That, or I write a tiny wrapper that lets me send json encoded message directly to a running `dart_language_server` and experiment till I figure out the right incantations.

I know I'm going to have "fun" trying to fix gitbash since the test for win32 fails inside - but objectively that is a secondary probably to getting it to work  on the cmd vim.

**Comment by natebosch** [comment]
@jtmcdole - I just published a new version of `dart_language_server` which corrected a bunch of windows path bugs. Can you try the latest and see if it makes any difference for you? It could be that the bugs were all on the server side. Let me know if it still looks like there are bugs on the client side.

**Comment by jtmcdole** [comment]
I'll do that as soon as I get home! Thanks!

**Comment by jtmcdole** [comment]
Running cmd + vim8+:
```shell
[lsc:Error] Failed to call textDocument/definition
[lsc:Error] Server status: not started
```
Running gitbash + vim8:
```shell
LSC Error!: [Analyzer RequestError method: analysis.getNavigation, code: GET_NAVIGATION_INVALID_FILE, message: Error during `analysis.getNavigation`: invalid file.]
```

**Comment by natebosch** [comment]
I know it's been way too long since I got around to digging on this.

I'm trying out a solution in https://github.com/natebosch/vim-lsc/pull/248

I don't normally use windows so I won't get much of a chance to run with this in my daily work - if anyone is following this issue and using windows regularly I'd appreciate any feedback on how things are working with that branch.

**Comment by natebosch** [comment]
I think this is fixed by https://github.com/natebosch/vim-lsc/pull/248
