### ISSUE TITLE
Chunk writes to the channel

### ISSUE THREAD

**Issue by natebosch** [natebosch/vim-lsc#67]
It seems like vim can get into a deadlock if we're trying to write a very large string to the channel at the same time as the server is trying to write a very large result back.

It's possible that if we split up the write into chunks and use a timer in between we can prevent this situation.

**Comment by prabirshrestha** [comment]
@natebosch I'm very interested in this too. I have been chasing this for too long in vim-lsp and have rewriten the lsp parser thinking I had bugs in my code. It happens when there is lot of data passing between client and server.

If this is really the bug would be good to also file the issue in https://github.com/vim/vim

**Comment by natebosch** [comment]
@prabirshrestha - Along with a change on the [server side](https://github.com/natebosch/dart_language_server/commit/68b59ee57e5c99f07f5b80a3ca4baba2d4010afc) this change is looking promising, but we didn't have a very reliable repro so it's hard to know for sure.

What pointed to this was that we could see both ends get 64K into writing a big message and then stop. I didn't check but I suspect 64K is the page size on that host. Our suspicion was that since both sides were single threaded they would get stuck on a write and it would block any further read so there would be a deadlock. Neither process was spinning the CPU when we checked.

I'd definitely like to file a bug for this. I need to find a stable and realistic repro... `cat` seems to be threaded so reads don't get blocked by writes.

I can repro with a ruby server and blocking IO - not sure if this is realistic though...

```ruby
#!/usr/bin/env ruby

while true
  data = STDIN.read(1024)
  STDOUT.write(data)
end
```

And on the vim side:

```viml
function! Ignore(channel, message) abort
endfunction

function! StartChannel() abort
  let options = {'in_io': 'pipe', 'in_mode': 'raw',
      \ 'out_io': 'pipe', 'out_mode': 'raw',
      \ 'out_cb': 'Ignore'}
  let job = job_start('./cat.rb', options)
  return job_getchannel(job)
endfunction

function! DumpData(channel) abort
  let long_message = 'abcde'
  while len(long_message) < (1024*100)
    let long_message .= long_message
  endwhile
  call ch_sendraw(a:channel, long_message)
endfunction
```

And I can use the same technique to fix it so that it does not get blocked:

```viml
function! Ignore(channel, message) abort
endfunction

function! StartChannel() abort
  let options = {'in_io': 'pipe', 'in_mode': 'raw',
      \ 'out_io': 'pipe', 'out_mode': 'raw',
      \ 'out_cb': 'Ignore'}
  let job = job_start('./cat.rb', options)
  let handle = {'channel': job_getchannel(job), 'buffer': ''}
  function! handle.send(message) abort
    let self.buffer .= a:message
    call self.flush(v:null)
  endfunction
  function! handle.flush(timer) abort
    if len(self.buffer) <= 1024
      call ch_sendraw(self.channel, self.buffer)
      let self.buffer = ''
    else
      let to_send = self.buffer[:1023]
      let self.buffer = self.buffer[1024:]
      call ch_sendraw(self.channel, to_send)
      call timer_start(0, self.flush)
    endif
  endfunction
  return handle
endfunction

function! DumpData(handle) abort
  let long_message = 'abcde'
  while len(long_message) < (1024*100)
    let long_message .= long_message
  endwhile
  call a:handle.send(long_message)
endfunction
```

**Comment by natebosch** [comment]
I think this is a fair repro... filed the issue here: https://github.com/vim/vim/issues/2548

**Comment by prabirshrestha** [comment]
@natebosch I'm making the same change for async.vim, Doesn't seem to hang yet. Will keep trying that patch for couple of days before I merge it. https://github.com/prabirshrestha/async.vim/pull/15
Thanks for the investigation as well as the fix.
