### ISSUE TITLE
Get all project errors

### ISSUE THREAD

**Issue by soywod** [natebosch/vim-lsc#86]
For now, we get all errors of the current file edited (in the loclist by default). Is there a way to get as well all project errors in the quickfix for example ?

**Comment by soywod** [comment]
I'm stupid, I just check back the doc and I found `:LSClientAllDiagnostics`. I dunno why I didn't see it on my first read.

**Comment by kika** [comment]
But thank you for that, @soywod , because I'm stupid too 👍
