### ISSUE TITLE
Server status: not started

### ISSUE THREAD

**Issue by GCorbel** [natebosch/vim-lsc#91]
Hello,

I tried to use `vim-lsc` with ruby and javascript files and I always have the message "Server status: not started".

I have this config lines for vim-lsc :  

```
let g:lsc_auto_map = v:true
let g:lsc_enable_autocomplete = v:true
let g:lsc_server_commands = {'ruby': 'solargraph socket', 'javascript': 'node /tmp/javascript-typescript-langserver/lib/language-server'}
let g:lsc_auto_map = {
    \ 'GoToDefinition': '<C-]>',
    \ 'FindReferences': 'gr',
    \ 'NextReference': '<C-n>',
    \ 'PreviousReference': '<C-p>',
    \ 'FindImplementations': 'gI',
    \ 'FindCodeActions': 'ga',
    \ 'DocumentSymbol': 'go',
    \ 'WorkspaceSymbol': 'gS',
    \ 'ShowHover': 'K',
    \ 'Completion': 'completefunc',
    \}
```

I try with this file : 

```
class Blabla
  def test
  end
end

blabla = Blabla.new
blabla.test
```

I have the error message when I go to `blabla.[test]` on the last line and I do `gr`.

The server is running because I have some results when I do `ps aux | grep solargraph`. Solargraph is launched when I go on Ruby file.

I have the exact same with Javascript files.

Do I have something more to do?

**Comment by natebosch** [comment]
It sounds like the server might not be responding to the initialize call, or the client might be failing to understand it. I'll need to get some subset of https://github.com/natebosch/vim-lsc/issues/19 implemented to make it easier to diagnose what might be happening.

In the mean time if you'd like to attempt to get a communication log you could try following https://github.com/natebosch/vim-lsc/wiki/Server-Debugging-Tips#logging-communication-across-stdio

**Comment by GCorbel** [comment]
Here is my `in.log` :
```
Content-Length: 374

{"method":"initialize","jsonrpc":"2.0","id":1,"params":{"rootUri":"file:///workspace/ my-project","capabilities":{"workspace":{"applyEdit":true},"textDocument":{"completion":{"snippetSupport":false},"synchronization":{"willSaveWaitUntil":false,"willSave":false,"didSave":false},"definition":{"dynamicRegistration":false}}},"processId":25759,"trace":"verbose"}}
```

And the `out.log` is exactly the same.

**Comment by GCorbel** [comment]
Sorry, there is nothing in `out.log`

**Comment by GCorbel** [comment]
When I start vim I have this message `[lsc:Error] StdErr from solargraph socket: Solargraph is listening PORT=7658 PID=21759`. It starts, solargraph but it gives an error.

**Comment by GCorbel** [comment]
With a JS file, I have : 

```
DEBUG Spawning 4 workers
DEBUG Worker 1 (PID 27624) online
DEBUG Worker 3 (PID 27635) online
DEBUG Worker 2 (PID 27629) online
DEBUG Worker 4 (PID 27641) online
INFO  Listening for incoming LSP connections on 2089
INFO  Listening for incoming LSP connections on 2089
INFO  Listening for incoming LSP connections on 2089
INFO  Listening for incoming LSP connections on 2089
```

I still have the error even if the server seems to be correctly started.

**Comment by natebosch** [comment]
> `Solargraph is listening PORT=7658`

Ah - that's the issue. `vim-lsc` by default expects to communicate over stdio (that's typical for most language servers but it looks like solargraph [doesn't support it](https://github.com/castwide/solargraph/issues/8#issuecomment-365730103)). To work over a socket we need a different configuration.

What you might need to do is start solargraph in a separate terminal, and configure your server in vim-lsc to be `'localhost:7658'`, or if you are using nvim `'nc localhost:7658`' (https://github.com/natebosch/vim-lsc/issues/83 would improve the nvim config)

Hopefully that port number is stable...

This workflow isn't ideal, but I'm not sure how feasible it would be to solve it. I filed https://github.com/natebosch/vim-lsc/issues/92 to track but I'm not expecting to be able to solve it anytime soon.

**Comment by GCorbel** [comment]
It's a little bit better but I have another error : 

```
Error detected while processing function <SNR>85_OnOpen[4]..lsc#file#onOpen[1]..lsc#server#start[3]..<SNR>100_Start[30]
..lsc#server#call[14]..276[3]..321[2]..322[2]..323:
line    1:
E906: not an open channel
```

**Comment by GCorbel** [comment]
With Javascript, I use `javascript-typescript-langserver` and I have this error on the node server side : 

```
/tmp/javascript-typescript-langserver/lib/util.js:46
    const pathParts = parts.pathname.split('/').map(segment => encodeURIComponent(decodeURIComponent(segment)));
                                                                                  ^

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at parts.pathname.split.map.segment (/tmp/javascript-typescript-langserver/lib/util.js:46:83)
    at Array.map (<anonymous>)
    at Object.normalizeUri (/tmp/javascript-typescript-langserver/lib/util.js:46:49)
    at Glob.globber.on (/tmp/javascript-typescript-langserver/lib/fs.js:62:40)
    at Glob.emit (events.js:180:13)
    at Glob._emitMatch (/tmp/javascript-typescript-langserver/node_modules/glob/glob.js:489:8)
    at Glob._processSimple2 (/tmp/javascript-typescript-langserver/node_modules/glob/glob.js:705:8)
    at /tmp/javascript-typescript-langserver/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/tmp/javascript-typescript-langserver/node_modules/glob/glob.js:789:10)
ERROR Worker 3 (PID 10951) exited from signal null with code 1, restarting
```

So it seems than the URL used is malformed.

**Comment by natebosch** [comment]
We're getting closer 😄 

I did notice this in the original logs: `"rootUri":"file:///workspace/ my-project"` which could explain this error. Does the directory have a space in it?

We do attempt to URI encode paths which should have replaced that space with something else: https://github.com/natebosch/vim-lsc/blob/35940465800105184e8d4a9b4c44fad020eb62bf/autoload/lsc/uri.vim#L7

I'm not quite sure what might be happening there...

**Comment by natebosch** [comment]
Does the URI look correct to you in the real logs? Anything odd in terms of special characters?

**Comment by GCorbel** [comment]
I got it! I added a `console.log` in the `lib/utils.js` of `javascript-typescript-langserver` and I have this which is parsed and make the script crash : 

`tmp/bundle/gems/railties-4.2.7.1/lib/rails/generators/rails/generator/templates/%file_name%_generator.rb.tt`

So this is not related to vim-lsc. I don't know if it's the same reason for `solargraph`.

**Comment by GCorbel** [comment]
Surprisingly, it seems to works with solargraph (with the host and port). I will try the rest of the day to be sure.

**Comment by GCorbel** [comment]
I close this issue because it works in `vim-lsc`. Maybe you should add a note about stdio and sockets.
